// Code generated by protoc-gen-go. DO NOT EDIT.
// source: home.proto

package home

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AD struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AD) Reset()         { *m = AD{} }
func (m *AD) String() string { return proto.CompactTextString(m) }
func (*AD) ProtoMessage()    {}
func (*AD) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{0}
}

func (m *AD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AD.Unmarshal(m, b)
}
func (m *AD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AD.Marshal(b, m, deterministic)
}
func (m *AD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AD.Merge(m, src)
}
func (m *AD) XXX_Size() int {
	return xxx_messageInfo_AD.Size(m)
}
func (m *AD) XXX_DiscardUnknown() {
	xxx_messageInfo_AD.DiscardUnknown(m)
}

var xxx_messageInfo_AD proto.InternalMessageInfo

func (m *AD) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *AD) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Rank struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName"`
	Dept                 string   `protobuf:"bytes,2,opt,name=dept,proto3" json:"dept"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count"`
	Id                   int64    `protobuf:"varint,4,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rank) Reset()         { *m = Rank{} }
func (m *Rank) String() string { return proto.CompactTextString(m) }
func (*Rank) ProtoMessage()    {}
func (*Rank) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{1}
}

func (m *Rank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rank.Unmarshal(m, b)
}
func (m *Rank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rank.Marshal(b, m, deterministic)
}
func (m *Rank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rank.Merge(m, src)
}
func (m *Rank) XXX_Size() int {
	return xxx_messageInfo_Rank.Size(m)
}
func (m *Rank) XXX_DiscardUnknown() {
	xxx_messageInfo_Rank.DiscardUnknown(m)
}

var xxx_messageInfo_Rank proto.InternalMessageInfo

func (m *Rank) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Rank) GetDept() string {
	if m != nil {
		return m.Dept
	}
	return ""
}

func (m *Rank) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Rank) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ServiceList struct {
	List                 []*Service `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total                int64      `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceList) Reset()         { *m = ServiceList{} }
func (m *ServiceList) String() string { return proto.CompactTextString(m) }
func (*ServiceList) ProtoMessage()    {}
func (*ServiceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{2}
}

func (m *ServiceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceList.Unmarshal(m, b)
}
func (m *ServiceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceList.Marshal(b, m, deterministic)
}
func (m *ServiceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceList.Merge(m, src)
}
func (m *ServiceList) XXX_Size() int {
	return xxx_messageInfo_ServiceList.Size(m)
}
func (m *ServiceList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceList proto.InternalMessageInfo

func (m *ServiceList) GetList() []*Service {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ServiceList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Service struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName"`
	Brief                string   `protobuf:"bytes,2,opt,name=brief,proto3" json:"brief"`
	Tag                  []string `protobuf:"bytes,3,rep,name=tag,proto3" json:"tag"`
	UpdateTime           string   `protobuf:"bytes,4,opt,name=updateTime,proto3" json:"updateTime"`
	ApplyStatus          int64    `protobuf:"varint,5,opt,name=applyStatus,proto3" json:"applyStatus"`
	CollectionStatus     int64    `protobuf:"varint,6,opt,name=collectionStatus,proto3" json:"collectionStatus"`
	Deliver              string   `protobuf:"bytes,7,opt,name=deliver,proto3" json:"deliver"`
	Id                   int64    `protobuf:"varint,8,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{3}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Service) GetBrief() string {
	if m != nil {
		return m.Brief
	}
	return ""
}

func (m *Service) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *Service) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Service) GetApplyStatus() int64 {
	if m != nil {
		return m.ApplyStatus
	}
	return 0
}

func (m *Service) GetCollectionStatus() int64 {
	if m != nil {
		return m.CollectionStatus
	}
	return 0
}

func (m *Service) GetDeliver() string {
	if m != nil {
		return m.Deliver
	}
	return ""
}

func (m *Service) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type HomeReq struct {
	Skip                 int64    `protobuf:"varint,1,opt,name=skip,proto3" json:"skip"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
	Sort                 *Sort    `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeReq) Reset()         { *m = HomeReq{} }
func (m *HomeReq) String() string { return proto.CompactTextString(m) }
func (*HomeReq) ProtoMessage()    {}
func (*HomeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{4}
}

func (m *HomeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeReq.Unmarshal(m, b)
}
func (m *HomeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeReq.Marshal(b, m, deterministic)
}
func (m *HomeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeReq.Merge(m, src)
}
func (m *HomeReq) XXX_Size() int {
	return xxx_messageInfo_HomeReq.Size(m)
}
func (m *HomeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeReq.DiscardUnknown(m)
}

var xxx_messageInfo_HomeReq proto.InternalMessageInfo

func (m *HomeReq) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *HomeReq) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *HomeReq) GetSort() *Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

type Sort struct {
	Column               string   `protobuf:"bytes,1,opt,name=column,proto3" json:"column"`
	Sort                 int64    `protobuf:"varint,2,opt,name=sort,proto3" json:"sort"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sort) Reset()         { *m = Sort{} }
func (m *Sort) String() string { return proto.CompactTextString(m) }
func (*Sort) ProtoMessage()    {}
func (*Sort) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{5}
}

func (m *Sort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sort.Unmarshal(m, b)
}
func (m *Sort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sort.Marshal(b, m, deterministic)
}
func (m *Sort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sort.Merge(m, src)
}
func (m *Sort) XXX_Size() int {
	return xxx_messageInfo_Sort.Size(m)
}
func (m *Sort) XXX_DiscardUnknown() {
	xxx_messageInfo_Sort.DiscardUnknown(m)
}

var xxx_messageInfo_Sort proto.InternalMessageInfo

func (m *Sort) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *Sort) GetSort() int64 {
	if m != nil {
		return m.Sort
	}
	return 0
}

// A2-服务列表
type ListReq struct {
	Skip                 int64    `protobuf:"varint,1,opt,name=skip,proto3" json:"skip"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
	Classify             string   `protobuf:"bytes,3,opt,name=classify,proto3" json:"classify"`
	Dept                 string   `protobuf:"bytes,4,opt,name=dept,proto3" json:"dept"`
	Deliver              string   `protobuf:"bytes,5,opt,name=deliver,proto3" json:"deliver"`
	ServiceType          string   `protobuf:"bytes,6,opt,name=serviceType,proto3" json:"serviceType"`
	Sort                 *Sort    `protobuf:"bytes,7,opt,name=sort,proto3" json:"sort"`
	ServiceName          string   `protobuf:"bytes,8,opt,name=serviceName,proto3" json:"serviceName"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReq) Reset()         { *m = ListReq{} }
func (m *ListReq) String() string { return proto.CompactTextString(m) }
func (*ListReq) ProtoMessage()    {}
func (*ListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{6}
}

func (m *ListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReq.Unmarshal(m, b)
}
func (m *ListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReq.Marshal(b, m, deterministic)
}
func (m *ListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReq.Merge(m, src)
}
func (m *ListReq) XXX_Size() int {
	return xxx_messageInfo_ListReq.Size(m)
}
func (m *ListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListReq proto.InternalMessageInfo

func (m *ListReq) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *ListReq) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListReq) GetClassify() string {
	if m != nil {
		return m.Classify
	}
	return ""
}

func (m *ListReq) GetDept() string {
	if m != nil {
		return m.Dept
	}
	return ""
}

func (m *ListReq) GetDeliver() string {
	if m != nil {
		return m.Deliver
	}
	return ""
}

func (m *ListReq) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *ListReq) GetSort() *Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *ListReq) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func init() {
	proto.RegisterType((*AD)(nil), "AD")
	proto.RegisterType((*Rank)(nil), "Rank")
	proto.RegisterType((*ServiceList)(nil), "ServiceList")
	proto.RegisterType((*Service)(nil), "Service")
	proto.RegisterType((*HomeReq)(nil), "HomeReq")
	proto.RegisterType((*Sort)(nil), "Sort")
	proto.RegisterType((*ListReq)(nil), "ListReq")
}

func init() { proto.RegisterFile("home.proto", fileDescriptor_711cc65aaf7510e9) }

var fileDescriptor_711cc65aaf7510e9 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x8a, 0xdb, 0x30,
	0x10, 0xc5, 0x96, 0x1d, 0x27, 0x13, 0x28, 0x8b, 0x58, 0x8a, 0x5a, 0x4a, 0x31, 0x3e, 0x85, 0x52,
	0x72, 0x48, 0xbf, 0x60, 0xa1, 0x87, 0x1e, 0xca, 0x1e, 0x94, 0xfd, 0x01, 0xc5, 0xd6, 0xa6, 0x62,
	0xe5, 0xc8, 0xb5, 0xc6, 0x0b, 0xf9, 0xd7, 0xfe, 0x41, 0x7f, 0xa2, 0x68, 0xac, 0x78, 0xdd, 0xe6,
	0xd2, 0xbd, 0xe9, 0x3d, 0x6b, 0x34, 0xef, 0xbd, 0x19, 0x03, 0xfc, 0x70, 0xad, 0xde, 0x76, 0xbd,
	0x43, 0x57, 0x7d, 0x86, 0xf4, 0xee, 0x2b, 0xbf, 0x85, 0xdc, 0xb4, 0xea, 0xa8, 0x45, 0x52, 0x26,
	0x9b, 0x95, 0x1c, 0x01, 0xbf, 0x01, 0x36, 0xf4, 0x56, 0xa4, 0xc4, 0x85, 0x63, 0x75, 0x80, 0x4c,
	0xaa, 0xd3, 0x13, 0x2f, 0x61, 0xed, 0x75, 0xff, 0x6c, 0x6a, 0x7d, 0xaf, 0xda, 0x4b, 0xd5, 0x9c,
	0xe2, 0x1c, 0xb2, 0x46, 0x77, 0x18, 0x8b, 0xe9, 0x1c, 0xba, 0xd4, 0x6e, 0x38, 0xa1, 0x60, 0x65,
	0xb2, 0x61, 0x72, 0x04, 0xfc, 0x0d, 0xa4, 0xa6, 0x11, 0x19, 0x51, 0xa9, 0x69, 0xaa, 0x3b, 0x58,
	0xef, 0xc7, 0x87, 0xbe, 0x1b, 0x8f, 0xfc, 0x03, 0x64, 0xd6, 0x78, 0x14, 0x49, 0xc9, 0x36, 0xeb,
	0xdd, 0x72, 0x1b, 0xbf, 0x49, 0x62, 0xc3, 0x93, 0xe8, 0x50, 0x8d, 0x22, 0x99, 0x1c, 0x41, 0xf5,
	0x3b, 0x81, 0x22, 0xde, 0xfb, 0x0f, 0xa9, 0xb7, 0x90, 0x1f, 0x7a, 0xa3, 0x1f, 0xa3, 0xd6, 0x11,
	0x04, 0xf3, 0xa8, 0x8e, 0x82, 0x95, 0x2c, 0x98, 0x47, 0x75, 0xe4, 0x1f, 0x01, 0x86, 0xae, 0x51,
	0xa8, 0x1f, 0x4c, 0xab, 0x49, 0xf0, 0x4a, 0xce, 0x98, 0xd0, 0x49, 0x75, 0x9d, 0x3d, 0xef, 0x51,
	0xe1, 0xe0, 0x45, 0x4e, 0x8a, 0xe6, 0x14, 0xff, 0x04, 0x37, 0xb5, 0xb3, 0x56, 0xd7, 0x68, 0xdc,
	0x29, 0x5e, 0x5b, 0xd0, 0xb5, 0x2b, 0x9e, 0x0b, 0x28, 0x1a, 0x6d, 0xcd, 0xb3, 0xee, 0x45, 0x41,
	0xad, 0x2e, 0x30, 0x06, 0xb6, 0x9c, 0x02, 0xbb, 0x87, 0xe2, 0x9b, 0x6b, 0xb5, 0xd4, 0x3f, 0x43,
	0xea, 0xfe, 0xc9, 0x74, 0xe4, 0x92, 0x49, 0x3a, 0x07, 0x7b, 0xd6, 0xb4, 0x06, 0x2f, 0x11, 0x11,
	0xe0, 0xef, 0x20, 0xf3, 0xae, 0x47, 0xb2, 0xb1, 0xde, 0xe5, 0xdb, 0xbd, 0xeb, 0x51, 0x12, 0x55,
	0xed, 0x20, 0x0b, 0x88, 0xbf, 0x85, 0x45, 0xed, 0xec, 0xd0, 0x9e, 0x62, 0x68, 0x11, 0x51, 0x93,
	0x50, 0x9a, 0xc6, 0x26, 0xa1, 0xe6, 0x57, 0x02, 0x45, 0x18, 0xd7, 0xeb, 0x44, 0xbc, 0x87, 0x65,
	0x6d, 0x95, 0xf7, 0xe6, 0xf1, 0x4c, 0x3b, 0xb1, 0x92, 0x13, 0x9e, 0x16, 0x28, 0x9b, 0x2d, 0xd0,
	0x2c, 0x93, 0xfc, 0xef, 0x4c, 0x5e, 0xa6, 0xfc, 0x70, 0xee, 0x34, 0x85, 0xfa, 0x32, 0xe5, 0x40,
	0x4d, 0x86, 0x8b, 0x2b, 0xc3, 0xff, 0xae, 0xc8, 0xf2, 0x6a, 0x45, 0x0e, 0x0b, 0xfa, 0x59, 0xbe,
	0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xce, 0xcf, 0x2e, 0x3a, 0x03, 0x00, 0x00,
}
