// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manage.proto

package manage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 服务发布信息
type Info struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	ServiceType          string      `protobuf:"bytes,3,opt,name=serviceType,proto3" json:"serviceType"`
	Classify             string      `protobuf:"bytes,4,opt,name=classify,proto3" json:"classify"`
	Deliver              []string    `protobuf:"bytes,5,rep,name=deliver,proto3" json:"deliver"`
	Tag                  []string    `protobuf:"bytes,6,rep,name=tag,proto3" json:"tag"`
	Brief                string      `protobuf:"bytes,7,opt,name=brief,proto3" json:"brief"`
	Status               int64       `protobuf:"varint,8,opt,name=status,proto3" json:"status"`
	Detail               string      `protobuf:"bytes,9,opt,name=detail,proto3" json:"detail"`
	Intro                string      `protobuf:"bytes,10,opt,name=intro,proto3" json:"intro"`
	Url                  string      `protobuf:"bytes,11,opt,name=url,proto3" json:"url"`
	File                 []*Document `protobuf:"bytes,12,rep,name=file,proto3" json:"file"`
	Image                []*Document `protobuf:"bytes,13,rep,name=image,proto3" json:"image"`
	Video                []*Document `protobuf:"bytes,14,rep,name=video,proto3" json:"video"`
	ChooseClassify       []string    `protobuf:"bytes,15,rep,name=chooseClassify,proto3" json:"chooseClassify"`
	ChooseDeliver        []string    `protobuf:"bytes,16,rep,name=chooseDeliver,proto3" json:"chooseDeliver"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{0}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Info) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Info) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *Info) GetClassify() string {
	if m != nil {
		return m.Classify
	}
	return ""
}

func (m *Info) GetDeliver() []string {
	if m != nil {
		return m.Deliver
	}
	return nil
}

func (m *Info) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *Info) GetBrief() string {
	if m != nil {
		return m.Brief
	}
	return ""
}

func (m *Info) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Info) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Info) GetIntro() string {
	if m != nil {
		return m.Intro
	}
	return ""
}

func (m *Info) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Info) GetFile() []*Document {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Info) GetImage() []*Document {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Info) GetVideo() []*Document {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *Info) GetChooseClassify() []string {
	if m != nil {
		return m.ChooseClassify
	}
	return nil
}

func (m *Info) GetChooseDeliver() []string {
	if m != nil {
		return m.ChooseDeliver
	}
	return nil
}

type Document struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{1}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Document) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// 服务发布条件查询请求
type Request struct {
	Type                 int64    `protobuf:"varint,1,opt,name=type,proto3" json:"type"`
	Skip                 int64    `protobuf:"varint,2,opt,name=skip,proto3" json:"skip"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit"`
	Serial               string   `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial"`
	Classify             string   `protobuf:"bytes,5,opt,name=classify,proto3" json:"classify"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name"`
	Deliver              []string `protobuf:"bytes,7,rep,name=deliver,proto3" json:"deliver"`
	Dept                 string   `protobuf:"bytes,8,opt,name=dept,proto3" json:"dept"`
	ServiceType          string   `protobuf:"bytes,10,opt,name=serviceType,proto3" json:"serviceType"`
	Status               int64    `protobuf:"varint,11,opt,name=status,proto3" json:"status"`
	Sort                 *Sort    `protobuf:"bytes,12,opt,name=sort,proto3" json:"sort"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Request) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *Request) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Request) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Request) GetClassify() string {
	if m != nil {
		return m.Classify
	}
	return ""
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetDeliver() []string {
	if m != nil {
		return m.Deliver
	}
	return nil
}

func (m *Request) GetDept() string {
	if m != nil {
		return m.Dept
	}
	return ""
}

func (m *Request) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *Request) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Request) GetSort() *Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

type Sort struct {
	Column               string   `protobuf:"bytes,1,opt,name=column,proto3" json:"column"`
	Sort                 int64    `protobuf:"varint,2,opt,name=sort,proto3" json:"sort"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sort) Reset()         { *m = Sort{} }
func (m *Sort) String() string { return proto.CompactTextString(m) }
func (*Sort) ProtoMessage()    {}
func (*Sort) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{3}
}

func (m *Sort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sort.Unmarshal(m, b)
}
func (m *Sort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sort.Marshal(b, m, deterministic)
}
func (m *Sort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sort.Merge(m, src)
}
func (m *Sort) XXX_Size() int {
	return xxx_messageInfo_Sort.Size(m)
}
func (m *Sort) XXX_DiscardUnknown() {
	xxx_messageInfo_Sort.DiscardUnknown(m)
}

var xxx_messageInfo_Sort proto.InternalMessageInfo

func (m *Sort) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *Sort) GetSort() int64 {
	if m != nil {
		return m.Sort
	}
	return 0
}

type Service struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Serial               string   `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial"`
	Classify             string   `protobuf:"bytes,5,opt,name=classify,proto3" json:"classify"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name"`
	Deliver              []string `protobuf:"bytes,7,rep,name=deliver,proto3" json:"deliver"`
	Dept                 string   `protobuf:"bytes,8,opt,name=dept,proto3" json:"dept"`
	Charge               string   `protobuf:"bytes,9,opt,name=charge,proto3" json:"charge"`
	ServiceType          string   `protobuf:"bytes,10,opt,name=serviceType,proto3" json:"serviceType"`
	Status               int64    `protobuf:"varint,11,opt,name=status,proto3" json:"status"`
	ApplyNumber          int64    `protobuf:"varint,12,opt,name=applyNumber,proto3" json:"applyNumber"`
	UpdateTime           string   `protobuf:"bytes,13,opt,name=updateTime,proto3" json:"updateTime"`
	MsgId                int64    `protobuf:"varint,14,opt,name=msgId,proto3" json:"msgId"`
	MsgStatus            int64    `protobuf:"varint,15,opt,name=msgStatus,proto3" json:"msgStatus"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{4}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Service) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Service) GetClassify() string {
	if m != nil {
		return m.Classify
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetDeliver() []string {
	if m != nil {
		return m.Deliver
	}
	return nil
}

func (m *Service) GetDept() string {
	if m != nil {
		return m.Dept
	}
	return ""
}

func (m *Service) GetCharge() string {
	if m != nil {
		return m.Charge
	}
	return ""
}

func (m *Service) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *Service) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Service) GetApplyNumber() int64 {
	if m != nil {
		return m.ApplyNumber
	}
	return 0
}

func (m *Service) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Service) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *Service) GetMsgStatus() int64 {
	if m != nil {
		return m.MsgStatus
	}
	return 0
}

type Response struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Data struct {
	List                 []*Service `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total                int64      `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	Classify             []string   `protobuf:"bytes,3,rep,name=classify,proto3" json:"classify"`
	Deliver              []string   `protobuf:"bytes,4,rep,name=deliver,proto3" json:"deliver"`
	Type                 []string   `protobuf:"bytes,5,rep,name=type,proto3" json:"type"`
	Dept                 []string   `protobuf:"bytes,6,rep,name=dept,proto3" json:"dept"`
	Pass                 int64      `protobuf:"varint,7,opt,name=pass,proto3" json:"pass"`
	Reject               int64      `protobuf:"varint,8,opt,name=reject,proto3" json:"reject"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{6}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetList() []*Service {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *Data) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Data) GetClassify() []string {
	if m != nil {
		return m.Classify
	}
	return nil
}

func (m *Data) GetDeliver() []string {
	if m != nil {
		return m.Deliver
	}
	return nil
}

func (m *Data) GetType() []string {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Data) GetDept() []string {
	if m != nil {
		return m.Dept
	}
	return nil
}

func (m *Data) GetPass() int64 {
	if m != nil {
		return m.Pass
	}
	return 0
}

func (m *Data) GetReject() int64 {
	if m != nil {
		return m.Reject
	}
	return 0
}

type ServiceDetail struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Deliver              []string    `protobuf:"bytes,3,rep,name=deliver,proto3" json:"deliver"`
	Classify             string      `protobuf:"bytes,4,opt,name=classify,proto3" json:"classify"`
	ServiceType          string      `protobuf:"bytes,5,opt,name=serviceType,proto3" json:"serviceType"`
	Dept                 string      `protobuf:"bytes,6,opt,name=dept,proto3" json:"dept"`
	Charge               string      `protobuf:"bytes,7,opt,name=charge,proto3" json:"charge"`
	UpdateTime           string      `protobuf:"bytes,8,opt,name=updateTime,proto3" json:"updateTime"`
	Tag                  []string    `protobuf:"bytes,9,rep,name=tag,proto3" json:"tag"`
	Brief                string      `protobuf:"bytes,10,opt,name=brief,proto3" json:"brief"`
	Detail               string      `protobuf:"bytes,11,opt,name=detail,proto3" json:"detail"`
	Intro                string      `protobuf:"bytes,12,opt,name=intro,proto3" json:"intro"`
	Url                  string      `protobuf:"bytes,13,opt,name=url,proto3" json:"url"`
	File                 []*Document `protobuf:"bytes,14,rep,name=file,proto3" json:"file"`
	Image                []*Document `protobuf:"bytes,15,rep,name=image,proto3" json:"image"`
	Video                []*Document `protobuf:"bytes,16,rep,name=video,proto3" json:"video"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServiceDetail) Reset()         { *m = ServiceDetail{} }
func (m *ServiceDetail) String() string { return proto.CompactTextString(m) }
func (*ServiceDetail) ProtoMessage()    {}
func (*ServiceDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{7}
}

func (m *ServiceDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDetail.Unmarshal(m, b)
}
func (m *ServiceDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDetail.Marshal(b, m, deterministic)
}
func (m *ServiceDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDetail.Merge(m, src)
}
func (m *ServiceDetail) XXX_Size() int {
	return xxx_messageInfo_ServiceDetail.Size(m)
}
func (m *ServiceDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDetail proto.InternalMessageInfo

func (m *ServiceDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ServiceDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceDetail) GetDeliver() []string {
	if m != nil {
		return m.Deliver
	}
	return nil
}

func (m *ServiceDetail) GetClassify() string {
	if m != nil {
		return m.Classify
	}
	return ""
}

func (m *ServiceDetail) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *ServiceDetail) GetDept() string {
	if m != nil {
		return m.Dept
	}
	return ""
}

func (m *ServiceDetail) GetCharge() string {
	if m != nil {
		return m.Charge
	}
	return ""
}

func (m *ServiceDetail) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *ServiceDetail) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *ServiceDetail) GetBrief() string {
	if m != nil {
		return m.Brief
	}
	return ""
}

func (m *ServiceDetail) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *ServiceDetail) GetIntro() string {
	if m != nil {
		return m.Intro
	}
	return ""
}

func (m *ServiceDetail) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ServiceDetail) GetFile() []*Document {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *ServiceDetail) GetImage() []*Document {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *ServiceDetail) GetVideo() []*Document {
	if m != nil {
		return m.Video
	}
	return nil
}

// 服务统计，包括申请总数，PV总数，每个月的申请数量，各个部门服务申请的数量
type RankReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Skip                 int64    `protobuf:"varint,2,opt,name=skip,proto3" json:"skip"`
	Order                string   `protobuf:"bytes,4,opt,name=order,proto3" json:"order"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RankReq) Reset()         { *m = RankReq{} }
func (m *RankReq) String() string { return proto.CompactTextString(m) }
func (*RankReq) ProtoMessage()    {}
func (*RankReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{8}
}

func (m *RankReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankReq.Unmarshal(m, b)
}
func (m *RankReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankReq.Marshal(b, m, deterministic)
}
func (m *RankReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankReq.Merge(m, src)
}
func (m *RankReq) XXX_Size() int {
	return xxx_messageInfo_RankReq.Size(m)
}
func (m *RankReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RankReq.DiscardUnknown(m)
}

var xxx_messageInfo_RankReq proto.InternalMessageInfo

func (m *RankReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RankReq) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *RankReq) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

type Statistics struct {
	Apply                []*ApplyStats `protobuf:"bytes,3,rep,name=apply,proto3" json:"apply"`
	Rank                 []*Rank       `protobuf:"bytes,4,rep,name=rank,proto3" json:"rank"`
	Total                int64         `protobuf:"varint,5,opt,name=total,proto3" json:"total"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Statistics) Reset()         { *m = Statistics{} }
func (m *Statistics) String() string { return proto.CompactTextString(m) }
func (*Statistics) ProtoMessage()    {}
func (*Statistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{9}
}

func (m *Statistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statistics.Unmarshal(m, b)
}
func (m *Statistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statistics.Marshal(b, m, deterministic)
}
func (m *Statistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statistics.Merge(m, src)
}
func (m *Statistics) XXX_Size() int {
	return xxx_messageInfo_Statistics.Size(m)
}
func (m *Statistics) XXX_DiscardUnknown() {
	xxx_messageInfo_Statistics.DiscardUnknown(m)
}

var xxx_messageInfo_Statistics proto.InternalMessageInfo

func (m *Statistics) GetApply() []*ApplyStats {
	if m != nil {
		return m.Apply
	}
	return nil
}

func (m *Statistics) GetRank() []*Rank {
	if m != nil {
		return m.Rank
	}
	return nil
}

func (m *Statistics) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ApplyStats struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyStats) Reset()         { *m = ApplyStats{} }
func (m *ApplyStats) String() string { return proto.CompactTextString(m) }
func (*ApplyStats) ProtoMessage()    {}
func (*ApplyStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{10}
}

func (m *ApplyStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyStats.Unmarshal(m, b)
}
func (m *ApplyStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyStats.Marshal(b, m, deterministic)
}
func (m *ApplyStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyStats.Merge(m, src)
}
func (m *ApplyStats) XXX_Size() int {
	return xxx_messageInfo_ApplyStats.Size(m)
}
func (m *ApplyStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyStats.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyStats proto.InternalMessageInfo

func (m *ApplyStats) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *ApplyStats) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Rank struct {
	Dept                 string   `protobuf:"bytes,1,opt,name=dept,proto3" json:"dept"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rank) Reset()         { *m = Rank{} }
func (m *Rank) String() string { return proto.CompactTextString(m) }
func (*Rank) ProtoMessage()    {}
func (*Rank) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{11}
}

func (m *Rank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rank.Unmarshal(m, b)
}
func (m *Rank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rank.Marshal(b, m, deterministic)
}
func (m *Rank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rank.Merge(m, src)
}
func (m *Rank) XXX_Size() int {
	return xxx_messageInfo_Rank.Size(m)
}
func (m *Rank) XXX_DiscardUnknown() {
	xxx_messageInfo_Rank.DiscardUnknown(m)
}

var xxx_messageInfo_Rank proto.InternalMessageInfo

func (m *Rank) GetDept() string {
	if m != nil {
		return m.Dept
	}
	return ""
}

func (m *Rank) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 消息管理
type SysReq struct {
	Skip                 int64    `protobuf:"varint,1,opt,name=skip,proto3" json:"skip"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
	Creator              string   `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator"`
	Mail                 string   `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail"`
	Status               int64    `protobuf:"varint,5,opt,name=status,proto3" json:"status"`
	Sort                 *Sort    `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysReq) Reset()         { *m = SysReq{} }
func (m *SysReq) String() string { return proto.CompactTextString(m) }
func (*SysReq) ProtoMessage()    {}
func (*SysReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{12}
}

func (m *SysReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysReq.Unmarshal(m, b)
}
func (m *SysReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysReq.Marshal(b, m, deterministic)
}
func (m *SysReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysReq.Merge(m, src)
}
func (m *SysReq) XXX_Size() int {
	return xxx_messageInfo_SysReq.Size(m)
}
func (m *SysReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SysReq.DiscardUnknown(m)
}

var xxx_messageInfo_SysReq proto.InternalMessageInfo

func (m *SysReq) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *SysReq) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SysReq) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *SysReq) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *SysReq) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SysReq) GetSort() *Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

type SysMsg struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content"`
	Creator              string   `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator"`
	Mail                 string   `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail"`
	CreateTime           string   `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime"`
	SendTime             string   `protobuf:"bytes,6,opt,name=sendTime,proto3" json:"sendTime"`
	Status               int64    `protobuf:"varint,7,opt,name=status,proto3" json:"status"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysMsg) Reset()         { *m = SysMsg{} }
func (m *SysMsg) String() string { return proto.CompactTextString(m) }
func (*SysMsg) ProtoMessage()    {}
func (*SysMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{13}
}

func (m *SysMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysMsg.Unmarshal(m, b)
}
func (m *SysMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysMsg.Marshal(b, m, deterministic)
}
func (m *SysMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysMsg.Merge(m, src)
}
func (m *SysMsg) XXX_Size() int {
	return xxx_messageInfo_SysMsg.Size(m)
}
func (m *SysMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SysMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SysMsg proto.InternalMessageInfo

func (m *SysMsg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SysMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SysMsg) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *SysMsg) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *SysMsg) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *SysMsg) GetSendTime() string {
	if m != nil {
		return m.SendTime
	}
	return ""
}

func (m *SysMsg) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type MsgList struct {
	List                 []*SysMsg `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total                int64     `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MsgList) Reset()         { *m = MsgList{} }
func (m *MsgList) String() string { return proto.CompactTextString(m) }
func (*MsgList) ProtoMessage()    {}
func (*MsgList) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{14}
}

func (m *MsgList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgList.Unmarshal(m, b)
}
func (m *MsgList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgList.Marshal(b, m, deterministic)
}
func (m *MsgList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgList.Merge(m, src)
}
func (m *MsgList) XXX_Size() int {
	return xxx_messageInfo_MsgList.Size(m)
}
func (m *MsgList) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgList.DiscardUnknown(m)
}

var xxx_messageInfo_MsgList proto.InternalMessageInfo

func (m *MsgList) GetList() []*SysMsg {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *MsgList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type SysMsgInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Creator              string   `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator"`
	CreateTime           string   `protobuf:"bytes,3,opt,name=createTime,proto3" json:"createTime"`
	StateTime            string   `protobuf:"bytes,4,opt,name=stateTime,proto3" json:"stateTime"`
	Status               int64    `protobuf:"varint,5,opt,name=status,proto3" json:"status"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysMsgInfo) Reset()         { *m = SysMsgInfo{} }
func (m *SysMsgInfo) String() string { return proto.CompactTextString(m) }
func (*SysMsgInfo) ProtoMessage()    {}
func (*SysMsgInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{15}
}

func (m *SysMsgInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysMsgInfo.Unmarshal(m, b)
}
func (m *SysMsgInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysMsgInfo.Marshal(b, m, deterministic)
}
func (m *SysMsgInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysMsgInfo.Merge(m, src)
}
func (m *SysMsgInfo) XXX_Size() int {
	return xxx_messageInfo_SysMsgInfo.Size(m)
}
func (m *SysMsgInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SysMsgInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SysMsgInfo proto.InternalMessageInfo

func (m *SysMsgInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SysMsgInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *SysMsgInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *SysMsgInfo) GetStateTime() string {
	if m != nil {
		return m.StateTime
	}
	return ""
}

func (m *SysMsgInfo) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SysMsgInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type NewMsg struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content"`
	Send                 bool     `protobuf:"varint,2,opt,name=send,proto3" json:"send"`
	SendTime             int64    `protobuf:"varint,3,opt,name=sendTime,proto3" json:"sendTime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMsg) Reset()         { *m = NewMsg{} }
func (m *NewMsg) String() string { return proto.CompactTextString(m) }
func (*NewMsg) ProtoMessage()    {}
func (*NewMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{16}
}

func (m *NewMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMsg.Unmarshal(m, b)
}
func (m *NewMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMsg.Marshal(b, m, deterministic)
}
func (m *NewMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMsg.Merge(m, src)
}
func (m *NewMsg) XXX_Size() int {
	return xxx_messageInfo_NewMsg.Size(m)
}
func (m *NewMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NewMsg proto.InternalMessageInfo

func (m *NewMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *NewMsg) GetSend() bool {
	if m != nil {
		return m.Send
	}
	return false
}

func (m *NewMsg) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Info)(nil), "Info")
	proto.RegisterType((*Document)(nil), "Document")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Sort)(nil), "Sort")
	proto.RegisterType((*Service)(nil), "Service")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Data)(nil), "Data")
	proto.RegisterType((*ServiceDetail)(nil), "ServiceDetail")
	proto.RegisterType((*RankReq)(nil), "RankReq")
	proto.RegisterType((*Statistics)(nil), "Statistics")
	proto.RegisterType((*ApplyStats)(nil), "ApplyStats")
	proto.RegisterType((*Rank)(nil), "Rank")
	proto.RegisterType((*SysReq)(nil), "SysReq")
	proto.RegisterType((*SysMsg)(nil), "SysMsg")
	proto.RegisterType((*MsgList)(nil), "MsgList")
	proto.RegisterType((*SysMsgInfo)(nil), "SysMsgInfo")
	proto.RegisterType((*NewMsg)(nil), "NewMsg")
}

func init() { proto.RegisterFile("manage.proto", fileDescriptor_519fa8ed5ffbbc8f) }

var fileDescriptor_519fa8ed5ffbbc8f = []byte{
	// 984 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcd, 0x8e, 0xe3, 0x44,
	0x10, 0x96, 0x63, 0x27, 0x4e, 0x2a, 0x33, 0x99, 0x51, 0x0b, 0xa1, 0x06, 0x86, 0x25, 0x58, 0x08,
	0xe5, 0x14, 0xad, 0x06, 0x89, 0x13, 0x17, 0xb4, 0x73, 0x59, 0x89, 0xdd, 0x43, 0x67, 0x1f, 0x80,
	0x1e, 0xbb, 0x27, 0xdb, 0x8c, 0xed, 0xce, 0xba, 0x3b, 0x83, 0xe6, 0x35, 0xe0, 0x05, 0x38, 0x71,
	0x47, 0xe2, 0x11, 0x78, 0x07, 0x5e, 0x07, 0x55, 0xb5, 0x9d, 0xd8, 0xb1, 0xd9, 0x01, 0x71, 0xe0,
	0x56, 0x55, 0xfd, 0x57, 0x55, 0xdf, 0x57, 0x9f, 0x0d, 0x67, 0x85, 0x2c, 0xe5, 0x56, 0xad, 0x77,
	0x95, 0x71, 0x26, 0xf9, 0x2d, 0x84, 0xe8, 0x65, 0x79, 0x67, 0xd8, 0x02, 0x46, 0x3a, 0xe3, 0xc1,
	0x32, 0x58, 0x85, 0x62, 0xa4, 0x33, 0xc6, 0x20, 0x2a, 0x65, 0xa1, 0xf8, 0x68, 0x19, 0xac, 0x66,
	0x82, 0x6c, 0xb6, 0x84, 0xb9, 0x55, 0xd5, 0x83, 0x4e, 0xd5, 0x9b, 0xc7, 0x9d, 0xe2, 0x21, 0x2d,
	0xb5, 0x43, 0xec, 0x63, 0x98, 0xa6, 0xb9, 0xb4, 0x56, 0xdf, 0x3d, 0xf2, 0x88, 0x96, 0x0f, 0x3e,
	0xe3, 0x10, 0x67, 0x2a, 0xd7, 0x0f, 0xaa, 0xe2, 0xe3, 0x65, 0xb8, 0x9a, 0x89, 0xc6, 0x65, 0x97,
	0x10, 0x3a, 0xb9, 0xe5, 0x13, 0x8a, 0xa2, 0xc9, 0x3e, 0x80, 0xf1, 0x6d, 0xa5, 0xd5, 0x1d, 0x8f,
	0xe9, 0x12, 0xef, 0xb0, 0x0f, 0x61, 0x62, 0x9d, 0x74, 0x7b, 0xcb, 0xa7, 0x94, 0x67, 0xed, 0x61,
	0x3c, 0x53, 0x4e, 0xea, 0x9c, 0xcf, 0x68, 0x7b, 0xed, 0xe1, 0x2d, 0xba, 0x74, 0x95, 0xe1, 0xe0,
	0x6f, 0x21, 0x07, 0x5f, 0xdb, 0x57, 0x39, 0x9f, 0x53, 0x0c, 0x4d, 0xf6, 0x29, 0x44, 0x77, 0x3a,
	0x57, 0xfc, 0x6c, 0x19, 0xae, 0xe6, 0xd7, 0xb3, 0xf5, 0x8d, 0x49, 0xf7, 0x85, 0x2a, 0x9d, 0xa0,
	0x30, 0xfb, 0x0c, 0xc6, 0xba, 0x90, 0x5b, 0xc5, 0xcf, 0x4f, 0xd7, 0x7d, 0x1c, 0x37, 0x3c, 0xe8,
	0x4c, 0x19, 0xbe, 0xe8, 0x6d, 0xa0, 0x38, 0xfb, 0x12, 0x16, 0xe9, 0x5b, 0x63, 0xac, 0x7a, 0xd1,
	0x34, 0xe7, 0x82, 0x6a, 0x3d, 0x89, 0xb2, 0x2f, 0xe0, 0xdc, 0x47, 0x6e, 0xea, 0x46, 0x5d, 0xd2,
	0xb6, 0x6e, 0x30, 0x79, 0x0e, 0xd3, 0xe6, 0x81, 0x03, 0x4c, 0x41, 0x0b, 0xa6, 0xba, 0xc0, 0xd1,
	0xa1, 0xc0, 0xe4, 0xa7, 0x11, 0xc4, 0x42, 0xbd, 0xdb, 0x2b, 0x4b, 0x27, 0x1c, 0xa2, 0xe7, 0xa1,
	0x26, 0x1b, 0x63, 0xf6, 0x5e, 0xef, 0xe8, 0x48, 0x28, 0xc8, 0xc6, 0xe6, 0xe5, 0xba, 0xd0, 0x8e,
	0x60, 0x0e, 0x85, 0x77, 0x08, 0x02, 0x55, 0x69, 0x99, 0xd7, 0xf0, 0xd6, 0x5e, 0x07, 0xf8, 0xf1,
	0x09, 0xf0, 0x4d, 0x8e, 0x93, 0x56, 0x8e, 0x2d, 0x32, 0xc4, 0x5d, 0x32, 0x30, 0x88, 0x32, 0xb5,
	0x73, 0x04, 0xf1, 0x4c, 0x90, 0x7d, 0x4a, 0x3c, 0xe8, 0x13, 0xef, 0x48, 0x8d, 0x79, 0x87, 0x1a,
	0x1f, 0x41, 0x64, 0x4d, 0xe5, 0xf8, 0xd9, 0x32, 0x58, 0xcd, 0xaf, 0xc7, 0xeb, 0x8d, 0xa9, 0x9c,
	0xa0, 0x50, 0x72, 0x0d, 0x11, 0x7a, 0x78, 0x34, 0x35, 0xf9, 0xbe, 0x28, 0xeb, 0x26, 0xd6, 0x1e,
	0x35, 0x05, 0x8f, 0x36, 0x4d, 0xc1, 0x33, 0x7f, 0x8e, 0x20, 0xde, 0xf8, 0x67, 0x7b, 0x13, 0xf3,
	0xff, 0xb4, 0x06, 0xb3, 0x7f, 0x2b, 0xab, 0xad, 0x6a, 0xb8, 0xef, 0xbd, 0xff, 0xd0, 0xb2, 0x25,
	0xcc, 0xe5, 0x6e, 0x97, 0x3f, 0xbe, 0xde, 0x17, 0xb7, 0xaa, 0xa2, 0xce, 0x85, 0xa2, 0x1d, 0x62,
	0xcf, 0x00, 0xf6, 0xbb, 0x4c, 0x3a, 0xf5, 0x46, 0x17, 0x38, 0x15, 0x78, 0x75, 0x2b, 0x82, 0xd4,
	0x29, 0xec, 0xf6, 0x65, 0xc6, 0x17, 0x9e, 0x3a, 0xe4, 0xb0, 0x2b, 0x98, 0x15, 0x76, 0xbb, 0xf1,
	0x4f, 0x5e, 0xd0, 0xca, 0x31, 0x90, 0x6c, 0x60, 0x2a, 0x94, 0xdd, 0x99, 0xd2, 0x12, 0x1d, 0x53,
	0x93, 0x1d, 0x28, 0x8a, 0x36, 0x02, 0x99, 0x49, 0x27, 0x09, 0x0d, 0x04, 0xf2, 0x46, 0x3a, 0x29,
	0x28, 0x84, 0x0d, 0x2b, 0x94, 0xb5, 0x38, 0xa1, 0x5e, 0x92, 0x1a, 0x37, 0xf9, 0x23, 0x80, 0x08,
	0x37, 0xb2, 0x2b, 0x88, 0x72, 0x6d, 0x1d, 0x0f, 0x68, 0x40, 0xa7, 0xeb, 0x1a, 0x43, 0x41, 0x51,
	0xcc, 0xd7, 0x19, 0x27, 0xf3, 0x1a, 0x6a, 0xef, 0x74, 0x70, 0x0b, 0x09, 0x88, 0x41, 0x2d, 0x8b,
	0x7a, 0x18, 0xd1, 0x78, 0x79, 0x89, 0x3b, 0x8c, 0x17, 0xe1, 0xe6, 0x05, 0xce, 0xe3, 0xc6, 0x20,
	0xda, 0x49, 0x6b, 0x49, 0xe0, 0x42, 0x41, 0x36, 0x22, 0x52, 0xa9, 0x1f, 0x54, 0xea, 0x1a, 0x7d,
	0xf3, 0x5e, 0xf2, 0x4b, 0x08, 0xe7, 0x75, 0xc6, 0x37, 0x5e, 0xd9, 0xfe, 0x89, 0x5a, 0xb7, 0x72,
	0x0c, 0xbb, 0x39, 0xbe, 0x4f, 0xa5, 0x4f, 0x78, 0x33, 0xee, 0xf3, 0xe6, 0x58, 0xcd, 0x10, 0x0b,
	0xe3, 0x0e, 0x0b, 0xbb, 0x4c, 0x99, 0xf6, 0x98, 0x52, 0x2b, 0xff, 0x6c, 0x40, 0xf9, 0xe1, 0x44,
	0xf9, 0x6b, 0x85, 0x9f, 0x0f, 0x2b, 0xfc, 0xd9, 0x80, 0xc2, 0x9f, 0xf7, 0x15, 0x7e, 0xf1, 0x84,
	0xc2, 0x5f, 0x3c, 0xa5, 0xf0, 0x97, 0xc3, 0x0a, 0x9f, 0xbc, 0x80, 0x58, 0xc8, 0xf2, 0x5e, 0xa8,
	0x77, 0x43, 0xd8, 0x0c, 0x89, 0xab, 0xa9, 0x32, 0x62, 0x0f, 0xe5, 0x4d, 0x4e, 0xf2, 0x3d, 0x00,
	0x4e, 0x83, 0xb6, 0x4e, 0xa7, 0x96, 0x7d, 0x0e, 0x63, 0x1a, 0x3a, 0x42, 0x6f, 0x7e, 0x3d, 0x5f,
	0x7f, 0x8b, 0x1e, 0x6e, 0xb0, 0xc2, 0xaf, 0xe0, 0x50, 0x54, 0xb2, 0xbc, 0x27, 0x0e, 0xe2, 0x50,
	0x50, 0x0a, 0x14, 0x3a, 0x72, 0x7a, 0xdc, 0xe2, 0x74, 0xf2, 0x35, 0xc0, 0xf1, 0x16, 0x42, 0x52,
	0xba, 0xc3, 0xc7, 0x03, 0x6d, 0x3c, 0x97, 0x9a, 0x7d, 0xd9, 0xc8, 0x9e, 0x77, 0x92, 0xe7, 0x10,
	0xe1, 0xdd, 0x07, 0xec, 0x83, 0x16, 0xf6, 0xc3, 0x27, 0x7e, 0x0e, 0x60, 0xb2, 0x79, 0xb4, 0xd8,
	0x90, 0xa6, 0x01, 0xc1, 0xd0, 0xd7, 0x65, 0xd4, 0xfe, 0xba, 0x70, 0x88, 0xd3, 0x4a, 0x49, 0x67,
	0xaa, 0x66, 0x92, 0x6b, 0x17, 0xef, 0x28, 0x10, 0x7e, 0xdf, 0x2f, 0xb2, 0x5b, 0x02, 0x36, 0x1e,
	0xd4, 0xfc, 0x49, 0x5f, 0xf3, 0x7f, 0xf7, 0x59, 0xbd, 0xb2, 0xdb, 0x1e, 0x4c, 0xf8, 0xb6, 0x29,
	0x9d, 0xaa, 0x0b, 0xc1, 0xb7, 0xbd, 0xfb, 0x2f, 0xb3, 0x7a, 0x06, 0x40, 0xcb, 0x9e, 0xf2, 0x7e,
	0x7e, 0x5a, 0x11, 0x1c, 0x3e, 0xab, 0xca, 0x8c, 0x56, 0xfd, 0x08, 0x1d, 0xfc, 0x56, 0x45, 0x71,
	0xbb, 0xa2, 0xe4, 0x1b, 0x88, 0x5f, 0xd9, 0xed, 0x77, 0xa8, 0x55, 0x9f, 0x74, 0x94, 0x2c, 0x5e,
	0xfb, 0x6a, 0xde, 0x27, 0x64, 0xc9, 0xaf, 0x01, 0x80, 0xdf, 0x36, 0xf8, 0xa7, 0xd7, 0x2a, 0x6f,
	0xd4, 0x2d, 0xaf, 0x5b, 0x4a, 0xd8, 0x2b, 0xe5, 0x0a, 0x66, 0x98, 0xa0, 0x5f, 0xf6, 0x3d, 0x38,
	0x06, 0xfe, 0x16, 0x9e, 0x56, 0xa3, 0x27, 0x9d, 0x46, 0x27, 0x02, 0x26, 0xaf, 0xd5, 0x8f, 0x08,
	0x4e, 0x6b, 0x4f, 0xd0, 0x05, 0x03, 0xc9, 0xa4, 0xca, 0x8c, 0x52, 0x9d, 0x0a, 0xb2, 0x3b, 0x2d,
	0xf5, 0x7f, 0x2b, 0x07, 0xff, 0x76, 0x42, 0xff, 0xb9, 0x5f, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff,
	0x29, 0x0a, 0x54, 0xa2, 0xf7, 0x0a, 0x00, 0x00,
}
