// Code generated by protoc-gen-go. DO NOT EDIT.
// source: detail.proto

package detail

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 服务详情
type Service struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Brief                string      `protobuf:"bytes,3,opt,name=brief,proto3" json:"brief"`
	Type                 string      `protobuf:"bytes,4,opt,name=type,proto3" json:"type"`
	Deliver              []string    `protobuf:"bytes,5,rep,name=deliver,proto3" json:"deliver"`
	Classify             string      `protobuf:"bytes,6,opt,name=classify,proto3" json:"classify"`
	Dept                 string      `protobuf:"bytes,7,opt,name=dept,proto3" json:"dept"`
	Charge               string      `protobuf:"bytes,8,opt,name=charge,proto3" json:"charge"`
	UpdateTime           string      `protobuf:"bytes,9,opt,name=updateTime,proto3" json:"updateTime"`
	Tag                  []string    `protobuf:"bytes,10,rep,name=tag,proto3" json:"tag"`
	Status               int64       `protobuf:"varint,11,opt,name=status,proto3" json:"status"`
	UseApplyStatus       int64       `protobuf:"varint,12,opt,name=useApplyStatus,proto3" json:"useApplyStatus"`
	ApplyStatus          int64       `protobuf:"varint,13,opt,name=applyStatus,proto3" json:"applyStatus"`
	CollectionStatus     int64       `protobuf:"varint,14,opt,name=collectionStatus,proto3" json:"collectionStatus"`
	Detail               string      `protobuf:"bytes,15,opt,name=detail,proto3" json:"detail"`
	Intro                string      `protobuf:"bytes,16,opt,name=intro,proto3" json:"intro"`
	Url                  string      `protobuf:"bytes,17,opt,name=url,proto3" json:"url"`
	File                 []*Document `protobuf:"bytes,18,rep,name=file,proto3" json:"file"`
	Image                []*Document `protobuf:"bytes,19,rep,name=image,proto3" json:"image"`
	Video                []*Document `protobuf:"bytes,20,rep,name=video,proto3" json:"video"`
	Count                int64       `protobuf:"varint,21,opt,name=count,proto3" json:"count"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ba7d873f5964269, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetBrief() string {
	if m != nil {
		return m.Brief
	}
	return ""
}

func (m *Service) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Service) GetDeliver() []string {
	if m != nil {
		return m.Deliver
	}
	return nil
}

func (m *Service) GetClassify() string {
	if m != nil {
		return m.Classify
	}
	return ""
}

func (m *Service) GetDept() string {
	if m != nil {
		return m.Dept
	}
	return ""
}

func (m *Service) GetCharge() string {
	if m != nil {
		return m.Charge
	}
	return ""
}

func (m *Service) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Service) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *Service) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Service) GetUseApplyStatus() int64 {
	if m != nil {
		return m.UseApplyStatus
	}
	return 0
}

func (m *Service) GetApplyStatus() int64 {
	if m != nil {
		return m.ApplyStatus
	}
	return 0
}

func (m *Service) GetCollectionStatus() int64 {
	if m != nil {
		return m.CollectionStatus
	}
	return 0
}

func (m *Service) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Service) GetIntro() string {
	if m != nil {
		return m.Intro
	}
	return ""
}

func (m *Service) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Service) GetFile() []*Document {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Service) GetImage() []*Document {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Service) GetVideo() []*Document {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *Service) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Document struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ba7d873f5964269, []int{1}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Document) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// 留言服务
// 1.显示留言
// 2.填写留言
type Comment struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	WriteTime            string   `protobuf:"bytes,3,opt,name=writeTime,proto3" json:"writeTime"`
	ServiceId            int64    `protobuf:"varint,4,opt,name=serviceId,proto3" json:"serviceId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ba7d873f5964269, []int{2}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Comment) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Comment) GetWriteTime() string {
	if m != nil {
		return m.WriteTime
	}
	return ""
}

func (m *Comment) GetServiceId() int64 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

// 查看留言信息
type CommRes struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommRes) Reset()         { *m = CommRes{} }
func (m *CommRes) String() string { return proto.CompactTextString(m) }
func (*CommRes) ProtoMessage()    {}
func (*CommRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ba7d873f5964269, []int{3}
}

func (m *CommRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommRes.Unmarshal(m, b)
}
func (m *CommRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommRes.Marshal(b, m, deterministic)
}
func (m *CommRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommRes.Merge(m, src)
}
func (m *CommRes) XXX_Size() int {
	return xxx_messageInfo_CommRes.Size(m)
}
func (m *CommRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CommRes.DiscardUnknown(m)
}

var xxx_messageInfo_CommRes proto.InternalMessageInfo

func (m *CommRes) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommRes) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CommRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Data struct {
	List                 []*Msg   `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ba7d873f5964269, []int{4}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetList() []*Msg {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *Data) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Msg struct {
	Commenter            string   `protobuf:"bytes,1,opt,name=commenter,proto3" json:"commenter"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content"`
	WriteTime            string   `protobuf:"bytes,3,opt,name=writeTime,proto3" json:"writeTime"`
	Respondent           string   `protobuf:"bytes,4,opt,name=respondent,proto3" json:"respondent"`
	Reply                string   `protobuf:"bytes,5,opt,name=reply,proto3" json:"reply"`
	ReplyTime            string   `protobuf:"bytes,6,opt,name=replyTime,proto3" json:"replyTime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ba7d873f5964269, []int{5}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetCommenter() string {
	if m != nil {
		return m.Commenter
	}
	return ""
}

func (m *Msg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Msg) GetWriteTime() string {
	if m != nil {
		return m.WriteTime
	}
	return ""
}

func (m *Msg) GetRespondent() string {
	if m != nil {
		return m.Respondent
	}
	return ""
}

func (m *Msg) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *Msg) GetReplyTime() string {
	if m != nil {
		return m.ReplyTime
	}
	return ""
}

func init() {
	proto.RegisterType((*Service)(nil), "Service")
	proto.RegisterType((*Document)(nil), "Document")
	proto.RegisterType((*Comment)(nil), "Comment")
	proto.RegisterType((*CommRes)(nil), "CommRes")
	proto.RegisterType((*Data)(nil), "Data")
	proto.RegisterType((*Msg)(nil), "Msg")
}

func init() { proto.RegisterFile("detail.proto", fileDescriptor_2ba7d873f5964269) }

var fileDescriptor_2ba7d873f5964269 = []byte{
	// 528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x63, 0xa7, 0x69, 0x26, 0xa5, 0x84, 0xa5, 0xa0, 0x01, 0x41, 0x89, 0x7c, 0x40, 0x11,
	0x87, 0x08, 0x15, 0x89, 0x3b, 0x22, 0x17, 0x0e, 0xbd, 0xb8, 0xfc, 0xc0, 0xd6, 0x3b, 0x09, 0x2b,
	0xd9, 0x5e, 0x6b, 0x77, 0x1d, 0x94, 0xaf, 0x82, 0x4f, 0x44, 0x3b, 0xeb, 0x24, 0xa6, 0x15, 0xe2,
	0x36, 0xef, 0xcd, 0xdb, 0x99, 0x37, 0x93, 0x71, 0xe0, 0x42, 0x91, 0x97, 0xba, 0x5a, 0xb5, 0xd6,
	0x78, 0x93, 0xff, 0xce, 0x60, 0x72, 0x47, 0x76, 0xa7, 0x4b, 0x12, 0x97, 0x30, 0xd2, 0x0a, 0x93,
	0x45, 0xb2, 0x4c, 0x8b, 0x91, 0x56, 0x42, 0x40, 0xd6, 0xc8, 0x9a, 0x70, 0xb4, 0x48, 0x96, 0xd3,
	0x82, 0x63, 0x71, 0x05, 0xe3, 0x7b, 0xab, 0x69, 0x83, 0x29, 0x93, 0x11, 0x04, 0xa5, 0xdf, 0xb7,
	0x84, 0x59, 0x54, 0x86, 0x58, 0x20, 0x4c, 0x14, 0x55, 0x7a, 0x47, 0x16, 0xc7, 0x8b, 0x74, 0x39,
	0x2d, 0x0e, 0x50, 0xbc, 0x86, 0xf3, 0xb2, 0x92, 0xce, 0xe9, 0xcd, 0x1e, 0xcf, 0xf8, 0xc5, 0x11,
	0x87, 0x4a, 0x8a, 0x5a, 0x8f, 0x93, 0x58, 0x29, 0xc4, 0xe2, 0x25, 0x9c, 0x95, 0x3f, 0xa4, 0xdd,
	0x12, 0x9e, 0x33, 0xdb, 0x23, 0x71, 0x0d, 0xd0, 0xb5, 0x4a, 0x7a, 0xfa, 0xae, 0x6b, 0xc2, 0x29,
	0xe7, 0x06, 0x8c, 0x98, 0x43, 0xea, 0xe5, 0x16, 0x81, 0xbb, 0x87, 0x30, 0x54, 0x72, 0x5e, 0xfa,
	0xce, 0xe1, 0x8c, 0xa7, 0xec, 0x91, 0x78, 0x0f, 0x97, 0x9d, 0xa3, 0x2f, 0x6d, 0x5b, 0xed, 0xef,
	0x62, 0xfe, 0x82, 0xf3, 0x0f, 0x58, 0xb1, 0x80, 0x99, 0x1c, 0x88, 0x9e, 0xb0, 0x68, 0x48, 0x89,
	0x0f, 0x30, 0x2f, 0x4d, 0x55, 0x51, 0xe9, 0xb5, 0x69, 0x7a, 0xd9, 0x25, 0xcb, 0x1e, 0xf1, 0xc1,
	0x4d, 0xfc, 0x2d, 0xf0, 0x69, 0x9c, 0x2b, 0xa2, 0xb0, 0x63, 0xdd, 0x78, 0x6b, 0x70, 0x1e, 0x77,
	0xcc, 0x20, 0x4c, 0xd3, 0xd9, 0x0a, 0x9f, 0x31, 0x17, 0x42, 0xf1, 0x16, 0xb2, 0x8d, 0xae, 0x08,
	0xc5, 0x22, 0x5d, 0xce, 0x6e, 0xa6, 0xab, 0xb5, 0x29, 0xbb, 0x9a, 0x1a, 0x5f, 0x30, 0x2d, 0xde,
	0xc1, 0x58, 0xd7, 0x72, 0x4b, 0xf8, 0xfc, 0x61, 0x3e, 0xf2, 0x41, 0xb0, 0xd3, 0x8a, 0x0c, 0x5e,
	0x3d, 0x12, 0x30, 0x1f, 0x8c, 0x94, 0xa6, 0x6b, 0x3c, 0xbe, 0xe0, 0x09, 0x22, 0xc8, 0x3f, 0xc2,
	0xf9, 0x41, 0x78, 0x3c, 0x91, 0x64, 0x70, 0x22, 0xbd, 0xd1, 0xd1, 0xd1, 0x68, 0xee, 0x60, 0xf2,
	0xd5, 0xd4, 0xff, 0x7c, 0x80, 0x30, 0xa9, 0xc9, 0xb9, 0x60, 0x35, 0x3e, 0x3a, 0x40, 0xf1, 0x06,
	0xa6, 0x3f, 0xad, 0xee, 0x7f, 0xe0, 0x78, 0x71, 0x27, 0x22, 0x64, 0x5d, 0x3c, 0xdd, 0x6f, 0x8a,
	0x4f, 0x2f, 0x2d, 0x4e, 0x44, 0x5e, 0xc4, 0xa6, 0x05, 0xb9, 0xd0, 0xb4, 0x34, 0x8a, 0xfa, 0xd3,
	0xe6, 0x58, 0xbc, 0x82, 0x4c, 0x49, 0x2f, 0xb9, 0xe3, 0xec, 0x66, 0xbc, 0x5a, 0x4b, 0x2f, 0x0b,
	0xa6, 0x86, 0x7e, 0xd2, 0xbf, 0xfc, 0xe4, 0x9f, 0x21, 0x5b, 0x47, 0x45, 0x56, 0x69, 0xe7, 0x31,
	0xe1, 0xc5, 0x65, 0xab, 0x5b, 0xb7, 0x2d, 0x98, 0x09, 0x2b, 0xf3, 0xc6, 0xcb, 0x38, 0x7e, 0x5a,
	0x44, 0x90, 0xff, 0x4a, 0x20, 0xbd, 0x75, 0xdb, 0xe0, 0xb8, 0x8c, 0x8b, 0x20, 0xdb, 0xaf, 0xe0,
	0x44, 0x84, 0xbe, 0xa5, 0x69, 0x3c, 0x35, 0xfe, 0xb0, 0x87, 0x1e, 0xfe, 0x67, 0x0f, 0xd7, 0x00,
	0x96, 0x5c, 0x6b, 0x1a, 0x15, 0x9e, 0xc6, 0x6f, 0x70, 0xc0, 0x04, 0x4f, 0x96, 0xda, 0x6a, 0x8f,
	0xe3, 0x78, 0x4f, 0x0c, 0x42, 0x4d, 0x0e, 0xb8, 0x66, 0xfc, 0x0c, 0x4f, 0xc4, 0xfd, 0x19, 0xff,
	0x3d, 0x7c, 0xfa, 0x13, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x40, 0x7a, 0x41, 0x2e, 0x04, 0x00, 0x00,
}
