// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgReq struct {
	Skip                 int64    `protobuf:"varint,1,opt,name=skip,proto3" json:"skip"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
	ServiceName          string   `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName"`
	Commenter            string   `protobuf:"bytes,4,opt,name=commenter,proto3" json:"commenter"`
	Show                 int64    `protobuf:"varint,5,opt,name=show,proto3" json:"show"`
	Sort                 *Sort    `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgReq) Reset()         { *m = MsgReq{} }
func (m *MsgReq) String() string { return proto.CompactTextString(m) }
func (*MsgReq) ProtoMessage()    {}
func (*MsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgReq.Unmarshal(m, b)
}
func (m *MsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgReq.Marshal(b, m, deterministic)
}
func (m *MsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReq.Merge(m, src)
}
func (m *MsgReq) XXX_Size() int {
	return xxx_messageInfo_MsgReq.Size(m)
}
func (m *MsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReq proto.InternalMessageInfo

func (m *MsgReq) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *MsgReq) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *MsgReq) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *MsgReq) GetCommenter() string {
	if m != nil {
		return m.Commenter
	}
	return ""
}

func (m *MsgReq) GetShow() int64 {
	if m != nil {
		return m.Show
	}
	return 0
}

func (m *MsgReq) GetSort() *Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

type Sort struct {
	Column               string   `protobuf:"bytes,1,opt,name=column,proto3" json:"column"`
	Sort                 int64    `protobuf:"varint,2,opt,name=sort,proto3" json:"sort"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sort) Reset()         { *m = Sort{} }
func (m *Sort) String() string { return proto.CompactTextString(m) }
func (*Sort) ProtoMessage()    {}
func (*Sort) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Sort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sort.Unmarshal(m, b)
}
func (m *Sort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sort.Marshal(b, m, deterministic)
}
func (m *Sort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sort.Merge(m, src)
}
func (m *Sort) XXX_Size() int {
	return xxx_messageInfo_Sort.Size(m)
}
func (m *Sort) XXX_DiscardUnknown() {
	xxx_messageInfo_Sort.DiscardUnknown(m)
}

var xxx_messageInfo_Sort proto.InternalMessageInfo

func (m *Sort) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *Sort) GetSort() int64 {
	if m != nil {
		return m.Sort
	}
	return 0
}

type MessageList struct {
	List                 []*Msg   `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	New                  int64    `protobuf:"varint,3,opt,name=new,proto3" json:"new"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageList) Reset()         { *m = MessageList{} }
func (m *MessageList) String() string { return proto.CompactTextString(m) }
func (*MessageList) ProtoMessage()    {}
func (*MessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *MessageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageList.Unmarshal(m, b)
}
func (m *MessageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageList.Marshal(b, m, deterministic)
}
func (m *MessageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageList.Merge(m, src)
}
func (m *MessageList) XXX_Size() int {
	return xxx_messageInfo_MessageList.Size(m)
}
func (m *MessageList) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageList.DiscardUnknown(m)
}

var xxx_messageInfo_MessageList proto.InternalMessageInfo

func (m *MessageList) GetList() []*Msg {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *MessageList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *MessageList) GetNew() int64 {
	if m != nil {
		return m.New
	}
	return 0
}

type Msg struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	ServiceName          string   `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName"`
	Commenter            string   `protobuf:"bytes,3,opt,name=commenter,proto3" json:"commenter"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content"`
	MsgTime              string   `protobuf:"bytes,5,opt,name=msgTime,proto3" json:"msgTime"`
	Read                 int64    `protobuf:"varint,6,opt,name=read,proto3" json:"read"`
	Reply                string   `protobuf:"bytes,7,opt,name=reply,proto3" json:"reply"`
	Show                 int64    `protobuf:"varint,8,opt,name=show,proto3" json:"show"`
	ServiceId            int64    `protobuf:"varint,9,opt,name=serviceId,proto3" json:"serviceId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Msg) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Msg) GetCommenter() string {
	if m != nil {
		return m.Commenter
	}
	return ""
}

func (m *Msg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Msg) GetMsgTime() string {
	if m != nil {
		return m.MsgTime
	}
	return ""
}

func (m *Msg) GetRead() int64 {
	if m != nil {
		return m.Read
	}
	return 0
}

func (m *Msg) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *Msg) GetShow() int64 {
	if m != nil {
		return m.Show
	}
	return 0
}

func (m *Msg) GetServiceId() int64 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

type MsgDetail struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Commenter            string   `protobuf:"bytes,2,opt,name=commenter,proto3" json:"commenter"`
	Tel                  string   `protobuf:"bytes,3,opt,name=tel,proto3" json:"tel"`
	ServiceName          string   `protobuf:"bytes,4,opt,name=serviceName,proto3" json:"serviceName"`
	ServiceId            int64    `protobuf:"varint,5,opt,name=serviceId,proto3" json:"serviceId"`
	MsgTime              string   `protobuf:"bytes,6,opt,name=msgTime,proto3" json:"msgTime"`
	Content              string   `protobuf:"bytes,7,opt,name=content,proto3" json:"content"`
	Respondent           string   `protobuf:"bytes,8,opt,name=respondent,proto3" json:"respondent"`
	Reply                string   `protobuf:"bytes,9,opt,name=reply,proto3" json:"reply"`
	ReplyTime            string   `protobuf:"bytes,10,opt,name=replyTime,proto3" json:"replyTime"`
	Show                 int64    `protobuf:"varint,11,opt,name=show,proto3" json:"show"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgDetail) Reset()         { *m = MsgDetail{} }
func (m *MsgDetail) String() string { return proto.CompactTextString(m) }
func (*MsgDetail) ProtoMessage()    {}
func (*MsgDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *MsgDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgDetail.Unmarshal(m, b)
}
func (m *MsgDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgDetail.Marshal(b, m, deterministic)
}
func (m *MsgDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDetail.Merge(m, src)
}
func (m *MsgDetail) XXX_Size() int {
	return xxx_messageInfo_MsgDetail.Size(m)
}
func (m *MsgDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDetail.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDetail proto.InternalMessageInfo

func (m *MsgDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgDetail) GetCommenter() string {
	if m != nil {
		return m.Commenter
	}
	return ""
}

func (m *MsgDetail) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *MsgDetail) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *MsgDetail) GetServiceId() int64 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *MsgDetail) GetMsgTime() string {
	if m != nil {
		return m.MsgTime
	}
	return ""
}

func (m *MsgDetail) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MsgDetail) GetRespondent() string {
	if m != nil {
		return m.Respondent
	}
	return ""
}

func (m *MsgDetail) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *MsgDetail) GetReplyTime() string {
	if m != nil {
		return m.ReplyTime
	}
	return ""
}

func (m *MsgDetail) GetShow() int64 {
	if m != nil {
		return m.Show
	}
	return 0
}

// 回复留言
type Reply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Reply                string   `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply"`
	ReplyTime            string   `protobuf:"bytes,3,opt,name=replyTime,proto3" json:"replyTime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Reply) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *Reply) GetReplyTime() string {
	if m != nil {
		return m.ReplyTime
	}
	return ""
}

// 更改状态
type Show struct {
	Ids                  []int64  `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids"`
	Show                 int64    `protobuf:"varint,3,opt,name=show,proto3" json:"show"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Show) Reset()         { *m = Show{} }
func (m *Show) String() string { return proto.CompactTextString(m) }
func (*Show) ProtoMessage()    {}
func (*Show) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *Show) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Show.Unmarshal(m, b)
}
func (m *Show) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Show.Marshal(b, m, deterministic)
}
func (m *Show) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Show.Merge(m, src)
}
func (m *Show) XXX_Size() int {
	return xxx_messageInfo_Show.Size(m)
}
func (m *Show) XXX_DiscardUnknown() {
	xxx_messageInfo_Show.DiscardUnknown(m)
}

var xxx_messageInfo_Show proto.InternalMessageInfo

func (m *Show) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *Show) GetShow() int64 {
	if m != nil {
		return m.Show
	}
	return 0
}

type Read struct {
	Ids                  []int64  `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids"`
	Read                 int64    `protobuf:"varint,3,opt,name=read,proto3" json:"read"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Read) Reset()         { *m = Read{} }
func (m *Read) String() string { return proto.CompactTextString(m) }
func (*Read) ProtoMessage()    {}
func (*Read) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *Read) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Read.Unmarshal(m, b)
}
func (m *Read) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Read.Marshal(b, m, deterministic)
}
func (m *Read) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Read.Merge(m, src)
}
func (m *Read) XXX_Size() int {
	return xxx_messageInfo_Read.Size(m)
}
func (m *Read) XXX_DiscardUnknown() {
	xxx_messageInfo_Read.DiscardUnknown(m)
}

var xxx_messageInfo_Read proto.InternalMessageInfo

func (m *Read) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *Read) GetRead() int64 {
	if m != nil {
		return m.Read
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgReq)(nil), "MsgReq")
	proto.RegisterType((*Sort)(nil), "Sort")
	proto.RegisterType((*MessageList)(nil), "MessageList")
	proto.RegisterType((*Msg)(nil), "Msg")
	proto.RegisterType((*MsgDetail)(nil), "MsgDetail")
	proto.RegisterType((*Reply)(nil), "Reply")
	proto.RegisterType((*Show)(nil), "Show")
	proto.RegisterType((*Read)(nil), "Read")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x41, 0xae, 0xd3, 0x30,
	0x10, 0x86, 0x15, 0xdb, 0x49, 0x9f, 0x27, 0x02, 0x55, 0x16, 0x42, 0x46, 0xaa, 0x50, 0x94, 0x55,
	0x17, 0x4f, 0x5d, 0x94, 0x2b, 0xb0, 0x41, 0x50, 0x90, 0xfc, 0xb8, 0x40, 0x68, 0xac, 0x3c, 0x8b,
	0x24, 0x2e, 0xb1, 0xa1, 0xe2, 0x38, 0xac, 0x38, 0x19, 0xf7, 0x40, 0x9e, 0xa4, 0x49, 0x1a, 0x8a,
	0xde, 0x6e, 0xe6, 0x9f, 0x38, 0xff, 0xfc, 0x5f, 0x1c, 0x78, 0xd6, 0x68, 0xe7, 0x8a, 0x4a, 0xef,
	0x4e, 0x9d, 0xf5, 0x36, 0xff, 0x15, 0x41, 0x72, 0x70, 0x95, 0xd2, 0xdf, 0x84, 0x00, 0xe6, 0xbe,
	0x9a, 0x93, 0x8c, 0xb2, 0x68, 0x4b, 0x15, 0xd6, 0xe2, 0x05, 0xc4, 0xb5, 0x69, 0x8c, 0x97, 0x04,
	0xc5, 0xbe, 0x11, 0x19, 0xa4, 0x4e, 0x77, 0x3f, 0xcc, 0x51, 0x7f, 0x2c, 0x1a, 0x2d, 0x69, 0x16,
	0x6d, 0xb9, 0x9a, 0x4b, 0x62, 0x03, 0xfc, 0x68, 0x9b, 0x46, 0xb7, 0x5e, 0x77, 0x92, 0xe1, 0x7c,
	0x12, 0xd0, 0xe9, 0xd1, 0x9e, 0x65, 0x3c, 0x38, 0x3d, 0xda, 0xb3, 0x78, 0x05, 0xcc, 0xd9, 0xce,
	0xcb, 0x24, 0x8b, 0xb6, 0xe9, 0x3e, 0xde, 0x3d, 0xd8, 0xce, 0x2b, 0x94, 0xf2, 0x3d, 0xb0, 0xd0,
	0x89, 0x97, 0x90, 0x1c, 0x6d, 0xfd, 0xbd, 0x69, 0x71, 0x45, 0xae, 0x86, 0x0e, 0x5f, 0x17, 0x8e,
	0x92, 0xe1, 0x75, 0xe1, 0xcc, 0x27, 0x48, 0x0f, 0x7d, 0xd0, 0x0f, 0xc6, 0x79, 0x21, 0x81, 0xd5,
	0xc6, 0x79, 0x19, 0x65, 0x74, 0x9b, 0xee, 0xd9, 0x2e, 0x44, 0x46, 0x25, 0x24, 0xf4, 0xd6, 0x17,
	0xf5, 0x25, 0x21, 0x36, 0x62, 0x0d, 0xb4, 0xd5, 0x67, 0x4c, 0x46, 0x55, 0x28, 0xf3, 0x3f, 0x11,
	0xd0, 0x83, 0xab, 0xc4, 0x73, 0x20, 0xa6, 0x1c, 0x18, 0x11, 0x53, 0x2e, 0x59, 0x90, 0x27, 0x58,
	0xd0, 0x25, 0x0b, 0x09, 0xab, 0xa3, 0x6d, 0xbd, 0x6e, 0xfd, 0xc0, 0xe9, 0xd2, 0x86, 0x49, 0xe3,
	0xaa, 0xcf, 0xa6, 0xd1, 0x08, 0x8a, 0xab, 0x4b, 0x1b, 0x02, 0x77, 0xba, 0x28, 0x91, 0x15, 0x55,
	0x58, 0x87, 0x1c, 0x9d, 0x3e, 0xd5, 0x3f, 0xe5, 0x0a, 0x9f, 0xed, 0x9b, 0x91, 0xf4, 0xdd, 0x8c,
	0xf4, 0x06, 0xf8, 0xb0, 0xde, 0xbb, 0x52, 0x72, 0x1c, 0x4c, 0x42, 0xfe, 0x9b, 0x00, 0x3f, 0xb8,
	0xea, 0xad, 0xf6, 0x85, 0xa9, 0xff, 0x49, 0x7b, 0x95, 0x85, 0x2c, 0xb3, 0xac, 0x81, 0x7a, 0x5d,
	0x0f, 0x19, 0x43, 0xb9, 0xa4, 0xc3, 0x6e, 0xd2, 0x99, 0xb6, 0x89, 0x17, 0xdb, 0xcc, 0x19, 0x24,
	0xd7, 0x0c, 0x66, 0xdc, 0x56, 0xd7, 0xdc, 0x5e, 0x03, 0x74, 0xda, 0x9d, 0x6c, 0x5b, 0x86, 0xe1,
	0x1d, 0x0e, 0x67, 0xca, 0x44, 0x8a, 0xcf, 0x49, 0x6d, 0x80, 0x63, 0x81, 0x5e, 0xd0, 0x27, 0x1b,
	0x85, 0x91, 0x63, 0x3a, 0x71, 0xcc, 0xdf, 0x43, 0xac, 0xf0, 0xe8, 0x12, 0xd2, 0x68, 0x40, 0xfe,
	0x6b, 0x40, 0x17, 0x06, 0xf9, 0x3d, 0xb0, 0x87, 0xf0, 0x71, 0xd6, 0x40, 0x4d, 0xe9, 0x24, 0xc9,
	0x68, 0xb8, 0x78, 0xa6, 0x74, 0xa3, 0x35, 0x9d, 0x59, 0xdf, 0x03, 0x53, 0xe1, 0xa3, 0xdf, 0x7c,
	0x1a, 0xaf, 0x06, 0x9d, 0xae, 0xc6, 0x97, 0x04, 0x7f, 0xf5, 0x37, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xc5, 0x79, 0xb4, 0x2a, 0xfb, 0x03, 0x00, 0x00,
}
