// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apply.proto

package apply

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 发布申请信息结构体
type Apply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Serial               string   `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial"`
	ServiceType          string   `protobuf:"bytes,3,opt,name=serviceType,proto3" json:"serviceType"`
	Deliver              []string `protobuf:"bytes,4,rep,name=deliver,proto3" json:"deliver"`
	Classify             string   `protobuf:"bytes,5,opt,name=classify,proto3" json:"classify"`
	Status               int64    `protobuf:"varint,6,opt,name=status,proto3" json:"status"`
	ApplyTime            string   `protobuf:"bytes,7,opt,name=applyTime,proto3" json:"applyTime"`
	StateTime            string   `protobuf:"bytes,8,opt,name=stateTime,proto3" json:"stateTime"`
	Data                 string   `protobuf:"bytes,9,opt,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Apply) Reset()         { *m = Apply{} }
func (m *Apply) String() string { return proto.CompactTextString(m) }
func (*Apply) ProtoMessage()    {}
func (*Apply) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{0}
}

func (m *Apply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Apply.Unmarshal(m, b)
}
func (m *Apply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Apply.Marshal(b, m, deterministic)
}
func (m *Apply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Apply.Merge(m, src)
}
func (m *Apply) XXX_Size() int {
	return xxx_messageInfo_Apply.Size(m)
}
func (m *Apply) XXX_DiscardUnknown() {
	xxx_messageInfo_Apply.DiscardUnknown(m)
}

var xxx_messageInfo_Apply proto.InternalMessageInfo

func (m *Apply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Apply) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Apply) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *Apply) GetDeliver() []string {
	if m != nil {
		return m.Deliver
	}
	return nil
}

func (m *Apply) GetClassify() string {
	if m != nil {
		return m.Classify
	}
	return ""
}

func (m *Apply) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Apply) GetApplyTime() string {
	if m != nil {
		return m.ApplyTime
	}
	return ""
}

func (m *Apply) GetStateTime() string {
	if m != nil {
		return m.StateTime
	}
	return ""
}

func (m *Apply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// 服务发布申请结构体
type Details struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Serial               string   `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial"`
	Classify             string   `protobuf:"bytes,3,opt,name=classify,proto3" json:"classify"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	Deliver              []string `protobuf:"bytes,5,rep,name=deliver,proto3" json:"deliver"`
	ServiceType          string   `protobuf:"bytes,6,opt,name=serviceType,proto3" json:"serviceType"`
	Status               int64    `protobuf:"varint,7,opt,name=status,proto3" json:"status"`
	UpdateTime           string   `protobuf:"bytes,8,opt,name=updateTime,proto3" json:"updateTime"`
	MsgId                int64    `protobuf:"varint,9,opt,name=msgId,proto3" json:"msgId"`
	MsgStatus            int64    `protobuf:"varint,10,opt,name=msgStatus,proto3" json:"msgStatus"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Details) Reset()         { *m = Details{} }
func (m *Details) String() string { return proto.CompactTextString(m) }
func (*Details) ProtoMessage()    {}
func (*Details) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{1}
}

func (m *Details) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Details.Unmarshal(m, b)
}
func (m *Details) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Details.Marshal(b, m, deterministic)
}
func (m *Details) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Details.Merge(m, src)
}
func (m *Details) XXX_Size() int {
	return xxx_messageInfo_Details.Size(m)
}
func (m *Details) XXX_DiscardUnknown() {
	xxx_messageInfo_Details.DiscardUnknown(m)
}

var xxx_messageInfo_Details proto.InternalMessageInfo

func (m *Details) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Details) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Details) GetClassify() string {
	if m != nil {
		return m.Classify
	}
	return ""
}

func (m *Details) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Details) GetDeliver() []string {
	if m != nil {
		return m.Deliver
	}
	return nil
}

func (m *Details) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *Details) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Details) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Details) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *Details) GetMsgStatus() int64 {
	if m != nil {
		return m.MsgStatus
	}
	return 0
}

// 服务发布申请结果查询
type Request struct {
	Tag                  int64    `protobuf:"varint,1,opt,name=tag,proto3" json:"tag"`
	Skip                 int64    `protobuf:"varint,2,opt,name=skip,proto3" json:"skip"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit"`
	Serial               string   `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial"`
	Classify             string   `protobuf:"bytes,5,opt,name=classify,proto3" json:"classify"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name"`
	Deliver              []string `protobuf:"bytes,7,rep,name=deliver,proto3" json:"deliver"`
	ServiceType          string   `protobuf:"bytes,8,opt,name=serviceType,proto3" json:"serviceType"`
	Status               int64    `protobuf:"varint,9,opt,name=status,proto3" json:"status"`
	Sort                 *Sort    `protobuf:"bytes,10,opt,name=sort,proto3" json:"sort"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetTag() int64 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *Request) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *Request) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Request) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Request) GetClassify() string {
	if m != nil {
		return m.Classify
	}
	return ""
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetDeliver() []string {
	if m != nil {
		return m.Deliver
	}
	return nil
}

func (m *Request) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *Request) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Request) GetSort() *Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

type Sort struct {
	Column               string   `protobuf:"bytes,1,opt,name=column,proto3" json:"column"`
	Sort                 int64    `protobuf:"varint,2,opt,name=sort,proto3" json:"sort"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sort) Reset()         { *m = Sort{} }
func (m *Sort) String() string { return proto.CompactTextString(m) }
func (*Sort) ProtoMessage()    {}
func (*Sort) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{3}
}

func (m *Sort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sort.Unmarshal(m, b)
}
func (m *Sort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sort.Marshal(b, m, deterministic)
}
func (m *Sort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sort.Merge(m, src)
}
func (m *Sort) XXX_Size() int {
	return xxx_messageInfo_Sort.Size(m)
}
func (m *Sort) XXX_DiscardUnknown() {
	xxx_messageInfo_Sort.DiscardUnknown(m)
}

var xxx_messageInfo_Sort proto.InternalMessageInfo

func (m *Sort) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *Sort) GetSort() int64 {
	if m != nil {
		return m.Sort
	}
	return 0
}

// 服务发布申请结果响应
type Response struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Data struct {
	List                 []*Details `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total                int64      `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	Pass                 int64      `protobuf:"varint,3,opt,name=pass,proto3" json:"pass"`
	Reject               int64      `protobuf:"varint,4,opt,name=reject,proto3" json:"reject"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{5}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetList() []*Details {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *Data) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Data) GetPass() int64 {
	if m != nil {
		return m.Pass
	}
	return 0
}

func (m *Data) GetReject() int64 {
	if m != nil {
		return m.Reject
	}
	return 0
}

//使用申请
type UseApply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Reason               string   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseApply) Reset()         { *m = UseApply{} }
func (m *UseApply) String() string { return proto.CompactTextString(m) }
func (*UseApply) ProtoMessage()    {}
func (*UseApply) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{6}
}

func (m *UseApply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseApply.Unmarshal(m, b)
}
func (m *UseApply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseApply.Marshal(b, m, deterministic)
}
func (m *UseApply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseApply.Merge(m, src)
}
func (m *UseApply) XXX_Size() int {
	return xxx_messageInfo_UseApply.Size(m)
}
func (m *UseApply) XXX_DiscardUnknown() {
	xxx_messageInfo_UseApply.DiscardUnknown(m)
}

var xxx_messageInfo_UseApply proto.InternalMessageInfo

func (m *UseApply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UseApply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UseApply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

//提交成功返回的数据
type Success struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Reason               string   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason"`
	Mail                 string   `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail"`
	Applicant            string   `protobuf:"bytes,5,opt,name=applicant,proto3" json:"applicant"`
	Dept                 string   `protobuf:"bytes,6,opt,name=dept,proto3" json:"dept"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Success) Reset()         { *m = Success{} }
func (m *Success) String() string { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()    {}
func (*Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{7}
}

func (m *Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Success.Unmarshal(m, b)
}
func (m *Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Success.Marshal(b, m, deterministic)
}
func (m *Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Success.Merge(m, src)
}
func (m *Success) XXX_Size() int {
	return xxx_messageInfo_Success.Size(m)
}
func (m *Success) XXX_DiscardUnknown() {
	xxx_messageInfo_Success.DiscardUnknown(m)
}

var xxx_messageInfo_Success proto.InternalMessageInfo

func (m *Success) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Success) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Success) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Success) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *Success) GetApplicant() string {
	if m != nil {
		return m.Applicant
	}
	return ""
}

func (m *Success) GetDept() string {
	if m != nil {
		return m.Dept
	}
	return ""
}

//查看使用申请信息
type UseApplication struct {
	Tag                  int64    `protobuf:"varint,1,opt,name=tag,proto3" json:"tag"`
	Skip                 int64    `protobuf:"varint,2,opt,name=skip,proto3" json:"skip"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit"`
	Serial               string   `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial"`
	ServiceName          string   `protobuf:"bytes,5,opt,name=serviceName,proto3" json:"serviceName"`
	ProjectName          string   `protobuf:"bytes,6,opt,name=projectName,proto3" json:"projectName"`
	Charge               string   `protobuf:"bytes,7,opt,name=charge,proto3" json:"charge"`
	Sort                 *Sort    `protobuf:"bytes,9,opt,name=sort,proto3" json:"sort"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseApplication) Reset()         { *m = UseApplication{} }
func (m *UseApplication) String() string { return proto.CompactTextString(m) }
func (*UseApplication) ProtoMessage()    {}
func (*UseApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{8}
}

func (m *UseApplication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseApplication.Unmarshal(m, b)
}
func (m *UseApplication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseApplication.Marshal(b, m, deterministic)
}
func (m *UseApplication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseApplication.Merge(m, src)
}
func (m *UseApplication) XXX_Size() int {
	return xxx_messageInfo_UseApplication.Size(m)
}
func (m *UseApplication) XXX_DiscardUnknown() {
	xxx_messageInfo_UseApplication.DiscardUnknown(m)
}

var xxx_messageInfo_UseApplication proto.InternalMessageInfo

func (m *UseApplication) GetTag() int64 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *UseApplication) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *UseApplication) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *UseApplication) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *UseApplication) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *UseApplication) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *UseApplication) GetCharge() string {
	if m != nil {
		return m.Charge
	}
	return ""
}

func (m *UseApplication) GetSort() *Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

//响应结果
type UseData struct {
	List                 []*UseInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total                int64      `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	Pass                 int64      `protobuf:"varint,3,opt,name=pass,proto3" json:"pass"`
	Reject               int64      `protobuf:"varint,4,opt,name=reject,proto3" json:"reject"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UseData) Reset()         { *m = UseData{} }
func (m *UseData) String() string { return proto.CompactTextString(m) }
func (*UseData) ProtoMessage()    {}
func (*UseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{9}
}

func (m *UseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseData.Unmarshal(m, b)
}
func (m *UseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseData.Marshal(b, m, deterministic)
}
func (m *UseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseData.Merge(m, src)
}
func (m *UseData) XXX_Size() int {
	return xxx_messageInfo_UseData.Size(m)
}
func (m *UseData) XXX_DiscardUnknown() {
	xxx_messageInfo_UseData.DiscardUnknown(m)
}

var xxx_messageInfo_UseData proto.InternalMessageInfo

func (m *UseData) GetList() []*UseInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *UseData) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UseData) GetPass() int64 {
	if m != nil {
		return m.Pass
	}
	return 0
}

func (m *UseData) GetReject() int64 {
	if m != nil {
		return m.Reject
	}
	return 0
}

type UseInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Serial               string   `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial"`
	ServiceName          string   `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName"`
	ProjectName          string   `protobuf:"bytes,4,opt,name=projectName,proto3" json:"projectName"`
	Charge               string   `protobuf:"bytes,5,opt,name=charge,proto3" json:"charge"`
	ApplyTime            string   `protobuf:"bytes,6,opt,name=applyTime,proto3" json:"applyTime"`
	Status               int64    `protobuf:"varint,7,opt,name=status,proto3" json:"status"`
	ServiceId            int64    `protobuf:"varint,8,opt,name=serviceId,proto3" json:"serviceId"`
	Update               bool     `protobuf:"varint,9,opt,name=update,proto3" json:"update"`
	MsgId                int64    `protobuf:"varint,10,opt,name=msgId,proto3" json:"msgId"`
	MsgStatus            int64    `protobuf:"varint,11,opt,name=msgStatus,proto3" json:"msgStatus"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseInfo) Reset()         { *m = UseInfo{} }
func (m *UseInfo) String() string { return proto.CompactTextString(m) }
func (*UseInfo) ProtoMessage()    {}
func (*UseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{10}
}

func (m *UseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseInfo.Unmarshal(m, b)
}
func (m *UseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseInfo.Marshal(b, m, deterministic)
}
func (m *UseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseInfo.Merge(m, src)
}
func (m *UseInfo) XXX_Size() int {
	return xxx_messageInfo_UseInfo.Size(m)
}
func (m *UseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UseInfo proto.InternalMessageInfo

func (m *UseInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UseInfo) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *UseInfo) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *UseInfo) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *UseInfo) GetCharge() string {
	if m != nil {
		return m.Charge
	}
	return ""
}

func (m *UseInfo) GetApplyTime() string {
	if m != nil {
		return m.ApplyTime
	}
	return ""
}

func (m *UseInfo) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UseInfo) GetServiceId() int64 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *UseInfo) GetUpdate() bool {
	if m != nil {
		return m.Update
	}
	return false
}

func (m *UseInfo) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *UseInfo) GetMsgStatus() int64 {
	if m != nil {
		return m.MsgStatus
	}
	return 0
}

//服务使用申请详情
type ApplyDetail struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service"`
	ServiceId            int64    `protobuf:"varint,2,opt,name=serviceId,proto3" json:"serviceId"`
	Serial               string   `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial"`
	Project              string   `protobuf:"bytes,4,opt,name=project,proto3" json:"project"`
	Reason               string   `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason"`
	ApplyTime            string   `protobuf:"bytes,6,opt,name=applyTime,proto3" json:"applyTime"`
	Status               int64    `protobuf:"varint,7,opt,name=status,proto3" json:"status"`
	StateTime            string   `protobuf:"bytes,8,opt,name=stateTime,proto3" json:"stateTime"`
	Data                 string   `protobuf:"bytes,9,opt,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyDetail) Reset()         { *m = ApplyDetail{} }
func (m *ApplyDetail) String() string { return proto.CompactTextString(m) }
func (*ApplyDetail) ProtoMessage()    {}
func (*ApplyDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{11}
}

func (m *ApplyDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyDetail.Unmarshal(m, b)
}
func (m *ApplyDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyDetail.Marshal(b, m, deterministic)
}
func (m *ApplyDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyDetail.Merge(m, src)
}
func (m *ApplyDetail) XXX_Size() int {
	return xxx_messageInfo_ApplyDetail.Size(m)
}
func (m *ApplyDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyDetail proto.InternalMessageInfo

func (m *ApplyDetail) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ApplyDetail) GetServiceId() int64 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *ApplyDetail) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *ApplyDetail) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ApplyDetail) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *ApplyDetail) GetApplyTime() string {
	if m != nil {
		return m.ApplyTime
	}
	return ""
}

func (m *ApplyDetail) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ApplyDetail) GetStateTime() string {
	if m != nil {
		return m.StateTime
	}
	return ""
}

func (m *ApplyDetail) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type UseRequest struct {
	Type                 int64    `protobuf:"varint,1,opt,name=type,proto3" json:"type"`
	Skip                 int64    `protobuf:"varint,2,opt,name=skip,proto3" json:"skip"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit"`
	Mail                 string   `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail"`
	Applicant            string   `protobuf:"bytes,5,opt,name=applicant,proto3" json:"applicant"`
	Serial               string   `protobuf:"bytes,6,opt,name=serial,proto3" json:"serial"`
	Service              string   `protobuf:"bytes,7,opt,name=service,proto3" json:"service"`
	Project              string   `protobuf:"bytes,8,opt,name=project,proto3" json:"project"`
	Charge               string   `protobuf:"bytes,9,opt,name=charge,proto3" json:"charge"`
	Sort                 *Sort    `protobuf:"bytes,10,opt,name=sort,proto3" json:"sort"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseRequest) Reset()         { *m = UseRequest{} }
func (m *UseRequest) String() string { return proto.CompactTextString(m) }
func (*UseRequest) ProtoMessage()    {}
func (*UseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{12}
}

func (m *UseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseRequest.Unmarshal(m, b)
}
func (m *UseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseRequest.Marshal(b, m, deterministic)
}
func (m *UseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseRequest.Merge(m, src)
}
func (m *UseRequest) XXX_Size() int {
	return xxx_messageInfo_UseRequest.Size(m)
}
func (m *UseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UseRequest proto.InternalMessageInfo

func (m *UseRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *UseRequest) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *UseRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *UseRequest) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *UseRequest) GetApplicant() string {
	if m != nil {
		return m.Applicant
	}
	return ""
}

func (m *UseRequest) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *UseRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *UseRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *UseRequest) GetCharge() string {
	if m != nil {
		return m.Charge
	}
	return ""
}

func (m *UseRequest) GetSort() *Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

type UseResponse struct {
	List                 []*List  `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	Pass                 int64    `protobuf:"varint,3,opt,name=pass,proto3" json:"pass"`
	Reject               int64    `protobuf:"varint,4,opt,name=reject,proto3" json:"reject"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseResponse) Reset()         { *m = UseResponse{} }
func (m *UseResponse) String() string { return proto.CompactTextString(m) }
func (*UseResponse) ProtoMessage()    {}
func (*UseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{13}
}

func (m *UseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseResponse.Unmarshal(m, b)
}
func (m *UseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseResponse.Marshal(b, m, deterministic)
}
func (m *UseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseResponse.Merge(m, src)
}
func (m *UseResponse) XXX_Size() int {
	return xxx_messageInfo_UseResponse.Size(m)
}
func (m *UseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UseResponse proto.InternalMessageInfo

func (m *UseResponse) GetList() []*List {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *UseResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UseResponse) GetPass() int64 {
	if m != nil {
		return m.Pass
	}
	return 0
}

func (m *UseResponse) GetReject() int64 {
	if m != nil {
		return m.Reject
	}
	return 0
}

type List struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Mail                 string   `protobuf:"bytes,2,opt,name=mail,proto3" json:"mail"`
	Applicant            string   `protobuf:"bytes,3,opt,name=applicant,proto3" json:"applicant"`
	Serial               string   `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial"`
	Service              string   `protobuf:"bytes,5,opt,name=service,proto3" json:"service"`
	Project              string   `protobuf:"bytes,7,opt,name=project,proto3" json:"project"`
	Charge               string   `protobuf:"bytes,8,opt,name=charge,proto3" json:"charge"`
	ApplyTime            string   `protobuf:"bytes,9,opt,name=applyTime,proto3" json:"applyTime"`
	Status               int64    `protobuf:"varint,10,opt,name=status,proto3" json:"status"`
	ServiceId            int64    `protobuf:"varint,11,opt,name=serviceId,proto3" json:"serviceId"`
	MsgId                int64    `protobuf:"varint,12,opt,name=msgId,proto3" json:"msgId"`
	MsgStatus            int64    `protobuf:"varint,13,opt,name=msgStatus,proto3" json:"msgStatus"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{14}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *List) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *List) GetApplicant() string {
	if m != nil {
		return m.Applicant
	}
	return ""
}

func (m *List) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *List) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *List) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *List) GetCharge() string {
	if m != nil {
		return m.Charge
	}
	return ""
}

func (m *List) GetApplyTime() string {
	if m != nil {
		return m.ApplyTime
	}
	return ""
}

func (m *List) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *List) GetServiceId() int64 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *List) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *List) GetMsgStatus() int64 {
	if m != nil {
		return m.MsgStatus
	}
	return 0
}

// A1-服务发布申请
type ServiceApply struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	ServiceType          string      `protobuf:"bytes,2,opt,name=serviceType,proto3" json:"serviceType"`
	Classify             string      `protobuf:"bytes,3,opt,name=classify,proto3" json:"classify"`
	Deliver              []string    `protobuf:"bytes,4,rep,name=deliver,proto3" json:"deliver"`
	Tag                  []string    `protobuf:"bytes,5,rep,name=tag,proto3" json:"tag"`
	Brief                string      `protobuf:"bytes,6,opt,name=brief,proto3" json:"brief"`
	Detail               string      `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail"`
	Intro                string      `protobuf:"bytes,8,opt,name=intro,proto3" json:"intro"`
	Url                  string      `protobuf:"bytes,9,opt,name=url,proto3" json:"url"`
	File                 []*Document `protobuf:"bytes,10,rep,name=file,proto3" json:"file"`
	Image                []*Document `protobuf:"bytes,11,rep,name=image,proto3" json:"image"`
	Video                []*Document `protobuf:"bytes,12,rep,name=video,proto3" json:"video"`
	Leader               string      `protobuf:"bytes,14,opt,name=leader,proto3" json:"leader"`
	Head                 string      `protobuf:"bytes,15,opt,name=head,proto3" json:"head"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServiceApply) Reset()         { *m = ServiceApply{} }
func (m *ServiceApply) String() string { return proto.CompactTextString(m) }
func (*ServiceApply) ProtoMessage()    {}
func (*ServiceApply) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{15}
}

func (m *ServiceApply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceApply.Unmarshal(m, b)
}
func (m *ServiceApply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceApply.Marshal(b, m, deterministic)
}
func (m *ServiceApply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceApply.Merge(m, src)
}
func (m *ServiceApply) XXX_Size() int {
	return xxx_messageInfo_ServiceApply.Size(m)
}
func (m *ServiceApply) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceApply.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceApply proto.InternalMessageInfo

func (m *ServiceApply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceApply) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *ServiceApply) GetClassify() string {
	if m != nil {
		return m.Classify
	}
	return ""
}

func (m *ServiceApply) GetDeliver() []string {
	if m != nil {
		return m.Deliver
	}
	return nil
}

func (m *ServiceApply) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *ServiceApply) GetBrief() string {
	if m != nil {
		return m.Brief
	}
	return ""
}

func (m *ServiceApply) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *ServiceApply) GetIntro() string {
	if m != nil {
		return m.Intro
	}
	return ""
}

func (m *ServiceApply) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ServiceApply) GetFile() []*Document {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *ServiceApply) GetImage() []*Document {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *ServiceApply) GetVideo() []*Document {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *ServiceApply) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *ServiceApply) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

type Document struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{16}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Document) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// 发布申请成功
type PublishSuccess struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Deliver              []string `protobuf:"bytes,3,rep,name=deliver,proto3" json:"deliver"`
	Mail                 string   `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail"`
	Charge               string   `protobuf:"bytes,5,opt,name=charge,proto3" json:"charge"`
	Dept                 string   `protobuf:"bytes,6,opt,name=dept,proto3" json:"dept"`
	Id                   int64    `protobuf:"varint,7,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishSuccess) Reset()         { *m = PublishSuccess{} }
func (m *PublishSuccess) String() string { return proto.CompactTextString(m) }
func (*PublishSuccess) ProtoMessage()    {}
func (*PublishSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_993661bab0ce9d1e, []int{17}
}

func (m *PublishSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishSuccess.Unmarshal(m, b)
}
func (m *PublishSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishSuccess.Marshal(b, m, deterministic)
}
func (m *PublishSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishSuccess.Merge(m, src)
}
func (m *PublishSuccess) XXX_Size() int {
	return xxx_messageInfo_PublishSuccess.Size(m)
}
func (m *PublishSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_PublishSuccess proto.InternalMessageInfo

func (m *PublishSuccess) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *PublishSuccess) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PublishSuccess) GetDeliver() []string {
	if m != nil {
		return m.Deliver
	}
	return nil
}

func (m *PublishSuccess) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *PublishSuccess) GetCharge() string {
	if m != nil {
		return m.Charge
	}
	return ""
}

func (m *PublishSuccess) GetDept() string {
	if m != nil {
		return m.Dept
	}
	return ""
}

func (m *PublishSuccess) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Apply)(nil), "Apply")
	proto.RegisterType((*Details)(nil), "Details")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Sort)(nil), "Sort")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Data)(nil), "Data")
	proto.RegisterType((*UseApply)(nil), "UseApply")
	proto.RegisterType((*Success)(nil), "Success")
	proto.RegisterType((*UseApplication)(nil), "UseApplication")
	proto.RegisterType((*UseData)(nil), "UseData")
	proto.RegisterType((*UseInfo)(nil), "UseInfo")
	proto.RegisterType((*ApplyDetail)(nil), "ApplyDetail")
	proto.RegisterType((*UseRequest)(nil), "UseRequest")
	proto.RegisterType((*UseResponse)(nil), "UseResponse")
	proto.RegisterType((*List)(nil), "List")
	proto.RegisterType((*ServiceApply)(nil), "ServiceApply")
	proto.RegisterType((*Document)(nil), "Document")
	proto.RegisterType((*PublishSuccess)(nil), "PublishSuccess")
}

func init() { proto.RegisterFile("apply.proto", fileDescriptor_993661bab0ce9d1e) }

var fileDescriptor_993661bab0ce9d1e = []byte{
	// 997 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x97, 0xcd, 0x6e, 0xe4, 0x44,
	0x10, 0xc7, 0xe5, 0xaf, 0xb1, 0xa7, 0x1c, 0x02, 0xb2, 0x56, 0xc8, 0x8b, 0x16, 0x88, 0x7c, 0xca,
	0x69, 0x84, 0xc2, 0x13, 0x20, 0x45, 0x48, 0x91, 0xd0, 0x0a, 0x79, 0x36, 0x0f, 0xd0, 0xb1, 0x7b,
	0x26, 0xbd, 0xf8, 0x0b, 0x77, 0x4f, 0xa4, 0x3c, 0x02, 0x67, 0xde, 0x81, 0x1b, 0x37, 0xde, 0x86,
	0x87, 0xe0, 0xc0, 0x81, 0x03, 0x1c, 0x50, 0x55, 0xb7, 0xc7, 0x1f, 0x63, 0x07, 0xb2, 0xda, 0xbd,
	0x75, 0x95, 0xfb, 0xab, 0x7e, 0x5d, 0xff, 0xea, 0x36, 0x84, 0xac, 0x69, 0x8a, 0xc7, 0x4d, 0xd3,
	0xd6, 0xaa, 0x4e, 0xfe, 0xb4, 0xc0, 0xfb, 0x06, 0xed, 0x28, 0x02, 0xb7, 0x62, 0x25, 0x8f, 0xad,
	0x0b, 0xeb, 0x72, 0x9d, 0x52, 0x3b, 0xfa, 0x14, 0x56, 0x92, 0xb7, 0x82, 0x15, 0xb1, 0x4d, 0x5e,
	0x63, 0x45, 0x17, 0x10, 0x4a, 0xde, 0x3e, 0x88, 0x8c, 0xbf, 0x79, 0x6c, 0x78, 0xec, 0xd0, 0xc7,
	0xa1, 0x2b, 0x8a, 0xc1, 0xcf, 0x79, 0x21, 0x1e, 0x78, 0x1b, 0xbb, 0x17, 0xce, 0xe5, 0x3a, 0xed,
	0xcc, 0xe8, 0x33, 0x08, 0xb2, 0x82, 0x49, 0x29, 0x76, 0x8f, 0xb1, 0x47, 0x03, 0x8f, 0x36, 0xad,
	0xa7, 0x98, 0x3a, 0xc8, 0x78, 0x75, 0x61, 0x5d, 0x3a, 0xa9, 0xb1, 0xa2, 0x57, 0xb0, 0xa6, 0x4d,
	0xbf, 0x11, 0x25, 0x8f, 0x7d, 0x1a, 0xd4, 0x3b, 0xf0, 0x2b, 0xf6, 0xe3, 0xf4, 0x35, 0xd0, 0x5f,
	0x8f, 0x0e, 0x8c, 0x2b, 0x67, 0x8a, 0xc5, 0x6b, 0x1d, 0x17, 0xb6, 0x93, 0x9f, 0x6c, 0xf0, 0xaf,
	0xb9, 0x62, 0xa2, 0x90, 0xd1, 0x39, 0xd8, 0x22, 0xa7, 0xa8, 0x9d, 0xd4, 0x16, 0xf9, 0x62, 0xcc,
	0xc3, 0x7d, 0x3b, 0x93, 0x7d, 0x77, 0xec, 0xdc, 0x01, 0xbb, 0x01, 0x01, 0x6f, 0x4c, 0x60, 0x42,
	0x6f, 0x75, 0x4a, 0xaf, 0xe7, 0xe0, 0x8f, 0x38, 0x7c, 0x01, 0x70, 0x68, 0xf2, 0x71, 0xa8, 0x03,
	0x4f, 0xf4, 0x02, 0xbc, 0x52, 0xee, 0x6f, 0x72, 0x0a, 0xd6, 0x49, 0xb5, 0x81, 0x7c, 0x4a, 0xb9,
	0xdf, 0xea, 0x09, 0x81, 0xbe, 0xf4, 0x8e, 0xe4, 0x1f, 0x0b, 0xfc, 0x94, 0xff, 0x78, 0xe0, 0x52,
	0x45, 0x9f, 0x80, 0xa3, 0xd8, 0xde, 0xc0, 0xc0, 0x26, 0x46, 0x26, 0x7f, 0x10, 0x0d, 0xb1, 0x70,
	0x52, 0x6a, 0xe3, 0x2a, 0x85, 0x28, 0x85, 0x22, 0x0c, 0x4e, 0xaa, 0x8d, 0x01, 0x37, 0x77, 0x91,
	0x9b, 0xb7, 0xc0, 0x6d, 0x35, 0xcf, 0xcd, 0x7f, 0x92, 0x5b, 0xf0, 0x14, 0xb7, 0xf5, 0x88, 0xdb,
	0x4b, 0x70, 0x65, 0xdd, 0x2a, 0x0a, 0x3e, 0xbc, 0xf2, 0x36, 0xdb, 0xba, 0x55, 0x29, 0xb9, 0x92,
	0x2b, 0x70, 0xd1, 0xc2, 0xa1, 0x59, 0x5d, 0x1c, 0xca, 0xca, 0x08, 0xc0, 0x58, 0x04, 0x00, 0x87,
	0x76, 0x00, 0x70, 0xcc, 0x16, 0x82, 0x94, 0xcb, 0xa6, 0xae, 0x24, 0xa5, 0x57, 0x56, 0xe7, 0xdc,
	0x30, 0xa3, 0x36, 0x2e, 0x47, 0x29, 0x67, 0x9b, 0xe5, 0xae, 0x99, 0x62, 0x3a, 0xf3, 0x30, 0xba,
	0x92, 0x4b, 0xc9, 0xf6, 0x9d, 0x6a, 0x3a, 0x33, 0xd9, 0x81, 0x8b, 0xfd, 0xa2, 0x57, 0xe0, 0x16,
	0x42, 0xaa, 0xd8, 0xba, 0x70, 0x2e, 0xc3, 0xab, 0x60, 0x63, 0xf2, 0x34, 0x25, 0x2f, 0xb2, 0x57,
	0xb5, 0x32, 0xc9, 0xe9, 0xa4, 0xda, 0xc0, 0x4d, 0x34, 0x4c, 0x4a, 0x73, 0x20, 0xd4, 0xc6, 0x80,
	0x5a, 0xfe, 0x96, 0x67, 0x8a, 0xce, 0xc3, 0x49, 0x8d, 0x95, 0x7c, 0x0b, 0xc1, 0xad, 0xe4, 0x5a,
	0xf3, 0xd3, 0xdc, 0xef, 0xce, 0xc3, 0x1e, 0xd7, 0x80, 0x96, 0x33, 0x59, 0x57, 0x66, 0xc3, 0xc6,
	0x4a, 0x7e, 0xb6, 0xc0, 0xdf, 0x1e, 0xb2, 0x8c, 0xeb, 0xb5, 0xcc, 0xd9, 0x5b, 0xa3, 0xb3, 0x7f,
	0xc6, 0x7c, 0xd8, 0xb7, 0x64, 0xa2, 0xcb, 0x1e, 0x6a, 0x77, 0xba, 0x17, 0x19, 0xab, 0x94, 0x49,
	0x9e, 0xde, 0x41, 0xca, 0xe6, 0x8d, 0xea, 0xb2, 0x07, 0xdb, 0xc9, 0xef, 0x16, 0x9c, 0x9b, 0xf0,
	0x44, 0xc6, 0x94, 0xa8, 0xab, 0x0f, 0x92, 0xd4, 0x7d, 0x2a, 0xbe, 0xc6, 0xf8, 0xbc, 0x51, 0x2a,
	0xa2, 0x0b, 0x7b, 0x34, 0x6d, 0x8d, 0xc4, 0x5f, 0xf7, 0x19, 0x3e, 0x74, 0x51, 0xc6, 0xdd, 0xb3,
	0x76, 0xdf, 0x55, 0x34, 0x63, 0x1d, 0x93, 0x75, 0x7d, 0x9a, 0xac, 0x02, 0xfc, 0x5b, 0xc9, 0x67,
	0xd3, 0xe4, 0x56, 0xf2, 0x9b, 0x6a, 0x57, 0xbf, 0xb7, 0x34, 0xf9, 0xd5, 0xa6, 0xb5, 0x70, 0xce,
	0xff, 0x5d, 0x22, 0x27, 0x54, 0x9c, 0xff, 0xa4, 0xe2, 0x3e, 0x45, 0xc5, 0x1b, 0x51, 0x19, 0x5d,
	0x01, 0xab, 0xe9, 0x15, 0xb0, 0x54, 0x30, 0xf1, 0x6a, 0xd0, 0xcb, 0xdf, 0xe4, 0x54, 0x30, 0x9c,
	0xb4, 0x77, 0xe0, 0x28, 0x5d, 0x3c, 0x89, 0x75, 0x90, 0x1a, 0xab, 0x2f, 0xa3, 0xb0, 0x58, 0x46,
	0xc3, 0x69, 0x19, 0xfd, 0xcb, 0x82, 0x90, 0x44, 0xa5, 0xf5, 0x8a, 0x42, 0x37, 0x0b, 0x19, 0x4d,
	0x74, 0xe6, 0x78, 0x4f, 0xf6, 0xcc, 0x9e, 0x0c, 0x5b, 0x67, 0xc4, 0x36, 0x06, 0xdf, 0x60, 0x32,
	0xd4, 0x3a, 0x73, 0x20, 0x28, 0x6f, 0x24, 0xa8, 0x77, 0x27, 0xf6, 0xbc, 0xcb, 0xf4, 0x6f, 0x0b,
	0xe0, 0x56, 0xf2, 0xee, 0x0e, 0x89, 0xc0, 0x55, 0x58, 0x9e, 0x4d, 0x41, 0xc4, 0xf6, 0x33, 0x04,
	0xf7, 0xfc, 0x2a, 0xd0, 0x03, 0x5b, 0x4d, 0x81, 0x75, 0x07, 0xe0, 0x8f, 0x0f, 0x60, 0x80, 0x32,
	0x38, 0x41, 0x69, 0x92, 0x6f, 0x3d, 0x2b, 0xc9, 0x99, 0xfb, 0xe3, 0x2d, 0x84, 0x14, 0xbc, 0xb9,
	0x0e, 0x5e, 0x8e, 0x64, 0xe9, 0x6d, 0xbe, 0x13, 0x52, 0xbd, 0x37, 0x4d, 0xfe, 0x66, 0x83, 0x8b,
	0x13, 0xce, 0xd5, 0x6d, 0xa2, 0x66, 0x2f, 0x51, 0x73, 0x96, 0xa9, 0xb9, 0x4b, 0xd4, 0xbc, 0x45,
	0x6a, 0xfe, 0x12, 0xb5, 0x60, 0x59, 0xb2, 0xeb, 0xe5, 0x04, 0x84, 0x65, 0xc9, 0x86, 0x53, 0x79,
	0x1c, 0xa5, 0x79, 0xb6, 0x28, 0xcd, 0x8f, 0xa6, 0xd2, 0xfc, 0xc3, 0x86, 0xb3, 0xad, 0x9e, 0x61,
	0xf9, 0xa9, 0x3b, 0x79, 0x5c, 0xd8, 0xa7, 0x8f, 0x8b, 0xa7, 0x1e, 0x80, 0xcb, 0xcf, 0x5d, 0x73,
	0xfb, 0xe8, 0x27, 0x20, 0xdd, 0x3e, 0x2f, 0xc0, 0xbb, 0x6b, 0x05, 0xdf, 0x99, 0x7c, 0xd5, 0x06,
	0xe2, 0xc8, 0xa9, 0x72, 0x74, 0xb7, 0x81, 0xb6, 0xb0, 0xb7, 0xa8, 0x54, 0x5b, 0x1b, 0xb6, 0xda,
	0xc0, 0x59, 0x0f, 0x6d, 0x61, 0xa0, 0x62, 0x33, 0xfa, 0x1c, 0xdc, 0x9d, 0x28, 0x78, 0x0c, 0x94,
	0x78, 0xeb, 0xcd, 0x75, 0x9d, 0x1d, 0x4a, 0x5e, 0xa9, 0x94, 0xdc, 0xd1, 0x97, 0xe0, 0x89, 0x12,
	0x5f, 0x1d, 0xe1, 0xf4, 0xbb, 0xf6, 0x63, 0x87, 0x07, 0x91, 0xf3, 0x3a, 0x3e, 0x3b, 0xe9, 0x40,
	0x7e, 0xdc, 0x60, 0xc1, 0x59, 0xce, 0xdb, 0xf8, 0x5c, 0x6f, 0x50, 0x5b, 0x08, 0xf3, 0x9e, 0xb3,
	0x3c, 0xfe, 0x58, 0xc3, 0xc4, 0x76, 0xf2, 0x15, 0x04, 0xdd, 0xf0, 0x59, 0xd8, 0x66, 0xfb, 0xf6,
	0x71, 0xfb, 0xc9, 0x2f, 0x16, 0x9c, 0x7f, 0x7f, 0xb8, 0x2b, 0x84, 0xbc, 0x7f, 0x97, 0x47, 0xc5,
	0x80, 0xbf, 0x33, 0xe6, 0x3f, 0x57, 0x50, 0x96, 0xee, 0x98, 0x99, 0x07, 0x85, 0x91, 0x9a, 0xdf,
	0x49, 0xed, 0x6e, 0x45, 0xff, 0x4d, 0x5f, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x4d, 0x4d,
	0xa1, 0x46, 0x0d, 0x00, 0x00,
}
