// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ad.proto

package ad

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 查询广告
type AdReq struct {
	Skip                 int64    `protobuf:"varint,1,opt,name=skip,proto3" json:"skip"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdReq) Reset()         { *m = AdReq{} }
func (m *AdReq) String() string { return proto.CompactTextString(m) }
func (*AdReq) ProtoMessage()    {}
func (*AdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{0}
}

func (m *AdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdReq.Unmarshal(m, b)
}
func (m *AdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdReq.Marshal(b, m, deterministic)
}
func (m *AdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdReq.Merge(m, src)
}
func (m *AdReq) XXX_Size() int {
	return xxx_messageInfo_AdReq.Size(m)
}
func (m *AdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdReq proto.InternalMessageInfo

func (m *AdReq) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *AdReq) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type AdRes struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Position             string   `protobuf:"bytes,2,opt,name=position,proto3" json:"position"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark"`
	UpdateTime           string   `protobuf:"bytes,4,opt,name=updateTime,proto3" json:"updateTime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdRes) Reset()         { *m = AdRes{} }
func (m *AdRes) String() string { return proto.CompactTextString(m) }
func (*AdRes) ProtoMessage()    {}
func (*AdRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{1}
}

func (m *AdRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdRes.Unmarshal(m, b)
}
func (m *AdRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdRes.Marshal(b, m, deterministic)
}
func (m *AdRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdRes.Merge(m, src)
}
func (m *AdRes) XXX_Size() int {
	return xxx_messageInfo_AdRes.Size(m)
}
func (m *AdRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AdRes.DiscardUnknown(m)
}

var xxx_messageInfo_AdRes proto.InternalMessageInfo

func (m *AdRes) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdRes) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *AdRes) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AdRes) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type AdModify struct {
	Aaa                  string     `protobuf:"bytes,1,opt,name=aaa,proto3" json:"aaa"`
	Remark               string     `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark"`
	Content              []*Content `protobuf:"bytes,3,rep,name=content,proto3" json:"content"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AdModify) Reset()         { *m = AdModify{} }
func (m *AdModify) String() string { return proto.CompactTextString(m) }
func (*AdModify) ProtoMessage()    {}
func (*AdModify) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{2}
}

func (m *AdModify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdModify.Unmarshal(m, b)
}
func (m *AdModify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdModify.Marshal(b, m, deterministic)
}
func (m *AdModify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdModify.Merge(m, src)
}
func (m *AdModify) XXX_Size() int {
	return xxx_messageInfo_AdModify.Size(m)
}
func (m *AdModify) XXX_DiscardUnknown() {
	xxx_messageInfo_AdModify.DiscardUnknown(m)
}

var xxx_messageInfo_AdModify proto.InternalMessageInfo

func (m *AdModify) GetAaa() string {
	if m != nil {
		return m.Aaa
	}
	return ""
}

func (m *AdModify) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AdModify) GetContent() []*Content {
	if m != nil {
		return m.Content
	}
	return nil
}

type Content struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{3}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Content) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type AdInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Position             string   `protobuf:"bytes,2,opt,name=position,proto3" json:"position"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark"`
	UpdateTime           string   `protobuf:"bytes,4,opt,name=updateTime,proto3" json:"updateTime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdInfo) Reset()         { *m = AdInfo{} }
func (m *AdInfo) String() string { return proto.CompactTextString(m) }
func (*AdInfo) ProtoMessage()    {}
func (*AdInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{4}
}

func (m *AdInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdInfo.Unmarshal(m, b)
}
func (m *AdInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdInfo.Marshal(b, m, deterministic)
}
func (m *AdInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdInfo.Merge(m, src)
}
func (m *AdInfo) XXX_Size() int {
	return xxx_messageInfo_AdInfo.Size(m)
}
func (m *AdInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AdInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AdInfo proto.InternalMessageInfo

func (m *AdInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdInfo) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *AdInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AdInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type AdList struct {
	List                 []*AdInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total                int64     `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AdList) Reset()         { *m = AdList{} }
func (m *AdList) String() string { return proto.CompactTextString(m) }
func (*AdList) ProtoMessage()    {}
func (*AdList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{5}
}

func (m *AdList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdList.Unmarshal(m, b)
}
func (m *AdList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdList.Marshal(b, m, deterministic)
}
func (m *AdList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdList.Merge(m, src)
}
func (m *AdList) XXX_Size() int {
	return xxx_messageInfo_AdList.Size(m)
}
func (m *AdList) XXX_DiscardUnknown() {
	xxx_messageInfo_AdList.DiscardUnknown(m)
}

var xxx_messageInfo_AdList proto.InternalMessageInfo

func (m *AdList) GetList() []*AdInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *AdList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*AdReq)(nil), "AdReq")
	proto.RegisterType((*AdRes)(nil), "AdRes")
	proto.RegisterType((*AdModify)(nil), "AdModify")
	proto.RegisterType((*Content)(nil), "Content")
	proto.RegisterType((*AdInfo)(nil), "AdInfo")
	proto.RegisterType((*AdList)(nil), "AdList")
}

func init() { proto.RegisterFile("ad.proto", fileDescriptor_8fe9fe9dbc34d4ab) }

var fileDescriptor_8fe9fe9dbc34d4ab = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x91, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0xc9, 0x9f, 0x4b, 0x72, 0x23, 0x88, 0x2c, 0x22, 0x8b, 0x82, 0x1c, 0x5b, 0x5d, 0x15,
	0x38, 0x2d, 0xad, 0x82, 0x95, 0xa0, 0xcd, 0x62, 0x61, 0xbb, 0xba, 0x7b, 0x32, 0xe4, 0xcf, 0xc6,
	0x64, 0xae, 0xf0, 0xdb, 0xcb, 0x4e, 0xf6, 0xe4, 0xfc, 0x02, 0x76, 0xf3, 0x7b, 0xc3, 0xbc, 0x99,
	0xc7, 0x40, 0x65, 0x6c, 0x3d, 0x4e, 0x9e, 0xbc, 0xda, 0xc1, 0xaa, 0xb1, 0xda, 0x7d, 0x09, 0x01,
	0xf9, 0xdc, 0xe2, 0x28, 0x93, 0x4d, 0xb2, 0xcd, 0x34, 0xd7, 0xe2, 0x12, 0x56, 0x1d, 0xf6, 0x48,
	0x32, 0x65, 0x71, 0x01, 0xd5, 0x2e, 0x23, 0xb3, 0x38, 0x87, 0x14, 0x6d, 0x1c, 0x48, 0xd1, 0x8a,
	0x6b, 0xa8, 0x46, 0x3f, 0x23, 0xa1, 0x1f, 0x78, 0x62, 0xad, 0x7f, 0x59, 0x5c, 0x41, 0x31, 0xb9,
	0xde, 0x4c, 0xad, 0xcc, 0xb8, 0x13, 0x49, 0xdc, 0x02, 0x1c, 0x46, 0x6b, 0xc8, 0xbd, 0x62, 0xef,
	0x64, 0xce, 0xbd, 0x13, 0x45, 0xbd, 0x41, 0xd5, 0xd8, 0x17, 0x6f, 0x71, 0xff, 0x2d, 0x2e, 0x20,
	0x33, 0xc6, 0xf0, 0xc2, 0xb5, 0x0e, 0xe5, 0x89, 0x6b, 0xfa, 0xc7, 0x55, 0x41, 0xf9, 0xe1, 0x07,
	0x72, 0x03, 0xc9, 0x6c, 0x93, 0x6d, 0xcf, 0xee, 0xaa, 0xfa, 0x71, 0x61, 0x7d, 0x6c, 0xa8, 0x1d,
	0x94, 0x51, 0x0b, 0x39, 0xb1, 0x37, 0x9f, 0x2e, 0x5a, 0x2f, 0x10, 0xd6, 0x1d, 0xa6, 0x2e, 0x3a,
	0x87, 0x52, 0x75, 0x50, 0x34, 0xf6, 0x69, 0xd8, 0xfb, 0x7f, 0x89, 0xfe, 0x10, 0xb6, 0x3d, 0xe3,
	0x4c, 0xe2, 0x06, 0xf2, 0x0e, 0x67, 0x92, 0x09, 0x67, 0x29, 0xeb, 0xe5, 0x08, 0xcd, 0x62, 0x38,
	0x9e, 0x3c, 0x99, 0xee, 0xf8, 0x24, 0x86, 0xf7, 0x82, 0xdf, 0x7b, 0xff, 0x13, 0x00, 0x00, 0xff,
	0xff, 0xc5, 0x7f, 0x86, 0x76, 0xea, 0x01, 0x00, 0x00,
}
